(()=>{
'use strict';
const TOKEN_KEY='prismaTeacherTokenV1';
const $=id=>document.getElementById(id);
let token=sessionStorage.getItem(TOKEN_KEY)||'',modules=[],bank=null,moduleKey='',unitIndex=0,questionId='',dirty=false,backups=[],toastTimer=null;
const typeNames={choice:'Selección única',truefalse:'Verdadero / Falso',short:'Respuesta corta',hangman:'Ahorcado',memory:'Memoria',match:'Relacionar',order:'Ordenar'};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function norm(v){return String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ')}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3200)}
async function req(path,{method='GET',json=null}={}){const headers={'X-PRISMA-Teacher-Token':token};if(json!==null)headers['Content-Type']='application/json';const r=await fetch(path,{method,headers,body:json===null?undefined:JSON.stringify(json),cache:'no-store'});const data=await r.json().catch(()=>({}));if(r.status===401){sessionStorage.removeItem(TOKEN_KEY);showLocked();throw new Error('Sesión docente requerida.')}if(!r.ok)throw new Error(data.detail||`Error ${r.status}`);return data}
function showLocked(){$('editorView').classList.add('hidden');$('lockedView').classList.remove('hidden')}
function setDirty(value=true){dirty=!!value;const el=$('saveState');el.textContent=dirty?'Cambios sin guardar':'Guardado';el.className='save-state '+(dirty?'dirty':'saved')}
function currentUnit(){return bank?.units?.[unitIndex]||null}
function currentQuestion(){return currentUnit()?.questions?.find(q=>q.id===questionId)||null}
function deep(v){return JSON.parse(JSON.stringify(v))}
function uniqueId(){const u=String(currentUnit()?.id??unitIndex+1).padStart(2,'0');return `${moduleKey}-custom-u${u}-${Date.now()}`}
function mark(){setDirty(true);renderQuestionList()}
function bind(id,event,fn){const el=$(id);if(el)el.addEventListener(event,fn)}
function renderModules(){const wanted=new URLSearchParams(location.search).get('module')||'measurement';$('moduleSelect').innerHTML=modules.map(m=>`<option value="${esc(m.key)}">${esc(m.icon)} ${esc(m.title)} · ${m.questions}</option>`).join('');const initial=modules.some(m=>m.key===wanted)?wanted:modules[0]?.key;if(initial){$('moduleSelect').value=initial;loadModule(initial)}}
async function loadModule(key){try{const x=await req(`/api/teacher/question_bank?module=${encodeURIComponent(key)}`);bank=x.bank;moduleKey=key;backups=x.backups||[];unitIndex=0;questionId='';setDirty(false);renderUnitSelect();renderBackups();selectFirstVisible()}catch(e){toast(e.message)}}
function renderUnitSelect(){const sel=$('unitSelect');sel.innerHTML=(bank.units||[]).map((u,i)=>`<option value="${i}">${i+1}. ${esc(u.title)} · ${(u.questions||[]).length}</option>`).join('');sel.value=String(unitIndex);renderReading();renderQuestionList()}
function selectFirstVisible(){const u=currentUnit();questionId=u?.questions?.[0]?.id||'';renderReading();renderQuestionList();renderQuestionEditor()}
function renderBackups(){$('backupSelect').innerHTML=backups.length?backups.map((b,i)=>`<option value="${esc(b.name)}">${i===0?'Última · ':''}${esc(b.created_at)} · ${b.size_kb} KB</option>`).join(''):'<option value="">Sin copias todavía</option>';}
function renderReading(){const u=currentUnit();if(!u)return;const r=u.reading||(u.reading={});$('unitTitle').value=u.title||'';$('unitIntro').value=u.intro||'';$('unitLesson').value=(u.lesson||[]).join('\n');$('readingTitle').value=r.title||'';$('readingLead').value=r.lead||'';$('readingContext').value=r.context||'';$('readingStrategy').value=r.strategy||'';$('readingRemember').value=r.remember||'';$('readingKeywords').value=(r.keywords||[]).join(', ');renderKeyIdeas()}
function renderKeyIdeas(){const u=currentUnit(),r=u.reading||(u.reading={}),ideas=Array.isArray(r.keyIdeas)?r.keyIdeas:(r.keyIdeas=[]);$('keyIdeasEditor').innerHTML=ideas.map((x,i)=>`<div class="key-idea-row" data-idea="${i}"><input data-k="title" value="${esc(x.title||'')}" placeholder="Título"><input data-k="text" value="${esc(x.text||'')}" placeholder="Explicación"><input data-k="example" value="${esc(x.example||'')}" placeholder="Ejemplo"><small>ID interno: ${esc(x.id||`k${i+1}`)}</small></div>`).join('');$('keyIdeasEditor').querySelectorAll('[data-idea] input').forEach(input=>input.oninput=e=>{const row=e.target.closest('[data-idea]'),idea=ideas[+row.dataset.idea];idea[e.target.dataset.k]=e.target.value;setDirty(true)})}
function renderQuestionList(){const u=currentUnit();if(!u)return;const query=norm($('searchInput').value);const visible=(u.questions||[]).map((q,i)=>({q,i})).filter(({q})=>!query||norm(`${q.id} ${q.type} ${q.prompt}`).includes(query));$('questionCount').textContent=`${u.questions.length} preguntas · ${visible.length} visibles`;$('questionList').innerHTML=visible.map(({q,i})=>`<button class="question-item ${q.id===questionId?'active':''}" data-qid="${esc(q.id)}" type="button"><span class="qnum">${i+1}</span><span><strong>${esc(q.prompt||'Sin enunciado')}</strong><small>${esc(typeNames[q.type]||q.type)} · ${esc(q.id)}</small></span></button>`).join('')||'<div class="empty-editor">No hay coincidencias.</div>';$('questionList').querySelectorAll('[data-qid]').forEach(b=>b.onclick=()=>{questionId=b.dataset.qid;renderQuestionList();renderQuestionEditor()})}
function renderQuestionEditor(){const q=currentQuestion();$('emptyEditor').classList.toggle('hidden',!!q);$('questionForm').classList.toggle('hidden',!q);if(!q)return;$('questionTypeBadge').textContent=typeNames[q.type]||q.type;$('questionIdLabel').textContent=q.id||'';$('questionPrompt').value=q.prompt||'';$('questionType').value=q.type||'choice';$('questionSkill').value=q.skill||'';$('questionExplanation').value=q.explanation||'';$('questionTime').value=q.time||40;$('questionReadingRef').value=q.readingRef||'';$('questionId').value=q.id||'';renderTypeEditor(q)}
function renderTypeEditor(q){const box=$('typeEditor');if(q.type==='choice'){q.options=Array.isArray(q.options)?q.options:['Respuesta correcta','Incorrecta 1','Incorrecta 2','Incorrecta 3'];if(!q.answer)q.answer=q.options[0]||'';box.innerHTML=`<h3>Opciones de respuesta</h3>${q.options.map((o,i)=>`<div class="option-row"><input type="radio" name="correctOption" data-correct="${i}" ${norm(o)===norm(q.answer)?'checked':''} aria-label="Marcar opción correcta"><input data-option="${i}" value="${esc(o)}" placeholder="Opción ${i+1}"><button class="mini-remove" data-remove-option="${i}" type="button" title="Quitar opción">×</button></div>`).join('')}<button id="addOptionBtn" class="secondary compact" type="button">＋ Agregar opción</button>`;box.querySelectorAll('[data-option]').forEach(inp=>inp.oninput=e=>{const i=+e.target.dataset.option,old=q.options[i],wasCorrect=norm(old)===norm(q.answer);q.options[i]=e.target.value;if(wasCorrect)q.answer=e.target.value;mark()});box.querySelectorAll('[data-correct]').forEach(r=>r.onchange=e=>{q.answer=q.options[+e.target.dataset.correct]||'';mark()});box.querySelectorAll('[data-remove-option]').forEach(b=>b.onclick=()=>{if(q.options.length<=2){toast('Debe haber al menos dos opciones.');return}const i=+b.dataset.removeOption,was=norm(q.options[i])===norm(q.answer);q.options.splice(i,1);if(was)q.answer=q.options[0]||'';mark();renderQuestionEditor()});$('addOptionBtn').onclick=()=>{if(q.options.length>=8){toast('Máximo 8 opciones.');return}q.options.push(`Nueva opción ${q.options.length+1}`);mark();renderQuestionEditor()};return}
if(q.type==='truefalse'){if(!['Verdadero','Falso'].includes(q.answer))q.answer='Verdadero';box.innerHTML=`<h3>Respuesta correcta</h3><select id="tfAnswer"><option ${q.answer==='Verdadero'?'selected':''}>Verdadero</option><option ${q.answer==='Falso'?'selected':''}>Falso</option></select>`;$('tfAnswer').onchange=e=>{q.answer=e.target.value;mark()};return}
if(q.type==='short'||q.type==='hangman'){box.innerHTML=`<h3>Respuesta esperada</h3><label>Respuesta<input id="simpleAnswer" value="${esc(q.answer||'')}"></label>${q.type==='short'?`<label>Respuestas aceptadas, separadas por coma<input id="acceptedAnswers" value="${esc((q.accepted||[q.answer]).filter(Boolean).join(', '))}"></label>`:''}`;$('simpleAnswer').oninput=e=>{q.answer=e.target.value;if(q.type==='short'&&(!Array.isArray(q.accepted)||!q.accepted.length))q.accepted=[e.target.value];mark()};if($('acceptedAnswers'))$('acceptedAnswers').oninput=e=>{q.accepted=e.target.value.split(',').map(x=>x.trim()).filter(Boolean);mark()};return}
if(q.type==='memory'||q.type==='match'){q.pairs=Array.isArray(q.pairs)?q.pairs:[];box.innerHTML=`<h3>Parejas</h3>${q.pairs.map((p,i)=>`<div class="pair-row"><input data-pair-left="${i}" value="${esc(p.left||'')}" placeholder="Elemento"><input data-pair-right="${i}" value="${esc(p.right||'')}" placeholder="Correspondencia"><button class="mini-remove" data-remove-pair="${i}" type="button">×</button></div>`).join('')}<button id="addPairBtn" class="secondary compact" type="button">＋ Agregar pareja</button>`;box.querySelectorAll('[data-pair-left]').forEach(x=>x.oninput=e=>{q.pairs[+e.target.dataset.pairLeft].left=e.target.value;mark()});box.querySelectorAll('[data-pair-right]').forEach(x=>x.oninput=e=>{q.pairs[+e.target.dataset.pairRight].right=e.target.value;mark()});box.querySelectorAll('[data-remove-pair]').forEach(b=>b.onclick=()=>{if(q.pairs.length<=2){toast('Debe haber al menos dos parejas.');return}q.pairs.splice(+b.dataset.removePair,1);mark();renderQuestionEditor()});$('addPairBtn').onclick=()=>{q.pairs.push({id:`p${q.pairs.length+1}`,left:`Elemento ${q.pairs.length+1}`,right:`Correspondencia ${q.pairs.length+1}`});mark();renderQuestionEditor()};return}
if(q.type==='order'){q.items=Array.isArray(q.items)?q.items:[];box.innerHTML=`<h3>Pasos en el orden correcto</h3>${q.items.map((item,i)=>`<div class="order-row"><b>${i+1}</b><input data-order="${i}" value="${esc(item)}"><button class="mini-remove" data-remove-order="${i}" type="button">×</button></div>`).join('')}<button id="addOrderBtn" class="secondary compact" type="button">＋ Agregar paso</button>`;box.querySelectorAll('[data-order]').forEach(x=>x.oninput=e=>{q.items[+e.target.dataset.order]=e.target.value;q.answerSummary=q.items.join(' → ');mark()});box.querySelectorAll('[data-remove-order]').forEach(b=>b.onclick=()=>{if(q.items.length<=2){toast('Debe haber al menos dos pasos.');return}q.items.splice(+b.dataset.removeOrder,1);q.answerSummary=q.items.join(' → ');mark();renderQuestionEditor()});$('addOrderBtn').onclick=()=>{q.items.push(`Paso ${q.items.length+1}`);q.answerSummary=q.items.join(' → ');mark();renderQuestionEditor()}}
}
function convertType(q,next){if(q.type===next)return;if(!confirm('Cambiar el tipo puede reemplazar opciones o datos específicos de esta pregunta. ¿Continuar?')){$('questionType').value=q.type;return}const oldAnswer=q.answer||q.answerSummary||'Respuesta correcta';for(const k of ['options','pairs','items','accepted','answerSummary','maxWrong'])delete q[k];q.type=next;if(next==='choice'){q.options=[oldAnswer,'Opción incorrecta 1','Opción incorrecta 2','Opción incorrecta 3'];q.answer=oldAnswer}else if(next==='truefalse'){q.answer='Verdadero'}else if(next==='short'){q.answer=oldAnswer;q.accepted=[oldAnswer]}else if(next==='hangman'){q.answer=oldAnswer;q.maxWrong=9}else if(next==='memory'||next==='match'){delete q.answer;q.pairs=[{id:'p1',left:'Elemento 1',right:'Correspondencia 1'},{id:'p2',left:'Elemento 2',right:'Correspondencia 2'}];q.answerSummary='Todas las parejas correctas'}else if(next==='order'){delete q.answer;q.items=['Paso 1','Paso 2','Paso 3'];q.answerSummary='Paso 1 → Paso 2 → Paso 3'}mark();renderQuestionEditor()}
function validateBank(){const issues=[],ids=new Set();for(let ui=0;ui<(bank?.units||[]).length;ui++){const u=bank.units[ui];if(!String(u.title||'').trim())issues.push(`Etapa ${ui+1}: falta el título.`);if(!Array.isArray(u.questions)||!u.questions.length){issues.push(`Etapa ${ui+1}: no tiene preguntas.`);continue}for(let qi=0;qi<u.questions.length;qi++){const q=u.questions[qi],where=`Etapa ${ui+1}, pregunta ${qi+1}`;if(!String(q.id||'').trim())issues.push(`${where}: falta el ID.`);else if(ids.has(q.id))issues.push(`${where}: ID repetido (${q.id}).`);else ids.add(q.id);if(!String(q.prompt||'').trim())issues.push(`${where}: falta el enunciado.`);if(q.type==='choice'){const opts=Array.isArray(q.options)?q.options:[],n=opts.map(norm);if(opts.length<2||opts.length>8)issues.push(`${where}: debe tener entre 2 y 8 opciones.`);if(n.some(x=>!x))issues.push(`${where}: hay opciones vacías.`);if(new Set(n).size!==n.length)issues.push(`${where}: hay opciones repetidas o demasiado parecidas.`);if(n.filter(x=>x===norm(q.answer)).length!==1)issues.push(`${where}: la respuesta correcta no aparece exactamente una vez.`)}if(q.type==='truefalse'&&!['verdadero','falso'].includes(norm(q.answer)))issues.push(`${where}: la respuesta debe ser Verdadero o Falso.`);if(['short','hangman'].includes(q.type)&&!String(q.answer||'').trim())issues.push(`${where}: falta la respuesta.`);if(['memory','match'].includes(q.type)&&(!Array.isArray(q.pairs)||q.pairs.length<2))issues.push(`${where}: faltan parejas.`);if(q.type==='order'&&(!Array.isArray(q.items)||q.items.length<2))issues.push(`${where}: faltan pasos.`)}}return issues}
function showValidation(issues){const b=$('validationBox');b.classList.remove('hidden','good');if(!issues.length){b.classList.add('good');b.textContent='✓ Banco válido. No se encontraron respuestas duplicadas ni errores estructurales.'}else b.textContent=`Se encontraron ${issues.length} problema(s):\n• `+issues.slice(0,18).join('\n• ')+(issues.length>18?'\n• …':'');b.scrollIntoView({behavior:'smooth',block:'nearest'})}
async function save(){const issues=validateBank();showValidation(issues);if(issues.length){toast('Corrige los problemas antes de guardar.');return}const btn=$('saveBtn');btn.disabled=true;btn.textContent='Guardando…';try{const x=await req('/api/teacher/question_bank/save',{method:'POST',json:{module:moduleKey,bank}});setDirty(false);toast(`Guardado. Copia creada: ${x.backup}`);const fresh=await req(`/api/teacher/question_bank?module=${encodeURIComponent(moduleKey)}`);bank=fresh.bank;backups=fresh.backups||[];renderBackups();renderUnitSelect();if(!currentQuestion())selectFirstVisible();else{renderQuestionList();renderQuestionEditor()}}catch(e){toast(e.message);showValidation(String(e.message).split('\n'))}finally{btn.disabled=false;btn.textContent='💾 Guardar cambios'}}
function newQuestion(){const u=currentUnit();const q={id:uniqueId(),type:'choice',prompt:'Escribe aquí una pregunta clara y completa.',options:['Respuesta correcta','Respuesta incorrecta 1','Respuesta incorrecta 2','Respuesta incorrecta 3'],answer:'Respuesta correcta',explanation:'Explica por qué esa es la única respuesta correcta.',time:40,skill:'pregunta personalizada',readingRef:'k1'};u.questions.push(q);questionId=q.id;mark();renderQuestionEditor();setTimeout(()=>$('questionPrompt').select(),0)}
function duplicateQuestion(){const q=currentQuestion(),u=currentUnit();if(!q)return;const copy=deep(q);copy.id=uniqueId();copy.prompt=`${q.prompt} (copia)`;const idx=u.questions.findIndex(x=>x.id===q.id);u.questions.splice(idx+1,0,copy);questionId=copy.id;mark();renderQuestionEditor()}
function deleteQuestion(){const u=currentUnit(),q=currentQuestion();if(!q)return;if(u.questions.length<=1){toast('La etapa debe conservar al menos una pregunta.');return}if(!confirm('¿Eliminar esta pregunta? El cambio no será definitivo hasta pulsar Guardar cambios.'))return;const idx=u.questions.findIndex(x=>x.id===q.id);u.questions.splice(idx,1);questionId=u.questions[Math.min(idx,u.questions.length-1)]?.id||'';mark();renderQuestionEditor()}
async function restore(){const name=$('backupSelect').value;if(!name){toast('No hay una copia seleccionada.');return}if(dirty&&!confirm('Tienes cambios sin guardar. Restaurar una copia los descartará. ¿Continuar?'))return;if(!confirm(`¿Restaurar la copia ${name}? PRISMA guardará antes una copia del estado actual.`))return;try{await req('/api/teacher/question_bank/restore',{method:'POST',json:{module:moduleKey,backup:name}});toast('Copia restaurada.');await loadModule(moduleKey)}catch(e){toast(e.message)}}
function exportJson(){if(!bank)return;const blob=new Blob([JSON.stringify(bank,null,2)],{type:'application/json;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`PRISMA_${moduleKey}_banco_preguntas.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importJson(file){if(!file)return;try{const data=JSON.parse(await file.text());if(data.moduleKey!==moduleKey)throw new Error(`El archivo pertenece al módulo ${data.moduleKey||'desconocido'}, no a ${moduleKey}.`);bank=data;unitIndex=0;questionId=bank.units?.[0]?.questions?.[0]?.id||'';setDirty(true);renderUnitSelect();renderQuestionEditor();showValidation(validateBank());toast('Banco importado. Revísalo y pulsa Guardar cambios para aplicarlo.')}catch(e){toast(`No se pudo importar: ${e.message}`)}finally{$('importInput').value=''}}
function wireReading(){bind('unitTitle','input',e=>{const u=currentUnit();u.title=e.target.value;setDirty(true);const opt=$('unitSelect').options[unitIndex];if(opt)opt.textContent=`${unitIndex+1}. ${u.title} · ${(u.questions||[]).length}`;});bind('unitIntro','input',e=>{currentUnit().intro=e.target.value;setDirty(true)});bind('unitLesson','input',e=>{currentUnit().lesson=e.target.value.split('\n').map(x=>x.trim()).filter(Boolean);setDirty(true)});for(const [id,key] of [['readingTitle','title'],['readingLead','lead'],['readingContext','context'],['readingStrategy','strategy'],['readingRemember','remember']])bind(id,'input',e=>{const u=currentUnit();u.reading||(u.reading={});u.reading[key]=e.target.value;setDirty(true)});bind('readingKeywords','input',e=>{const u=currentUnit();u.reading||(u.reading={});u.reading.keywords=e.target.value.split(',').map(x=>x.trim()).filter(Boolean);setDirty(true)});bind('addKeyIdeaBtn','click',()=>{const u=currentUnit();u.reading||(u.reading={});const a=u.reading.keyIdeas||(u.reading.keyIdeas=[]);let n=1,ids=new Set(a.map(x=>x.id));while(ids.has(`k${n}`))n++;a.push({id:`k${n}`,title:`Idea clave ${n}`,text:'Escribe aquí la explicación.',example:'Escribe aquí un ejemplo.'});setDirty(true);renderKeyIdeas()})}
function wireQuestion(){bind('questionPrompt','input',e=>{const q=currentQuestion();q.prompt=e.target.value;mark()});bind('questionSkill','input',e=>{currentQuestion().skill=e.target.value;setDirty(true)});bind('questionExplanation','input',e=>{currentQuestion().explanation=e.target.value;setDirty(true)});bind('questionTime','input',e=>{currentQuestion().time=Math.max(10,Math.min(300,+e.target.value||40));setDirty(true)});bind('questionReadingRef','input',e=>{currentQuestion().readingRef=e.target.value;setDirty(true)});bind('questionId','change',e=>{const q=currentQuestion(),old=q.id,next=e.target.value.trim();if(!next){e.target.value=old;toast('El ID no puede quedar vacío.');return}if(bank.units.some(u=>u.questions.some(x=>x!==q&&x.id===next))){e.target.value=old;toast('Ese ID ya existe en el banco.');return}q.id=next;questionId=next;mark();renderQuestionEditor()});bind('questionType','change',e=>convertType(currentQuestion(),e.target.value));bind('duplicateBtn','click',duplicateQuestion);bind('deleteBtn','click',deleteQuestion);bind('newQuestionBtn','click',newQuestion)}
async function boot(){if(!token){showLocked();return}try{const x=await req('/api/teacher/question_banks');modules=x.modules||[];if(!modules.length)throw new Error('No se encontraron bancos curriculares.');$('lockedView').classList.add('hidden');$('editorView').classList.remove('hidden');renderModules()}catch(e){if(!/Sesión docente/.test(e.message))toast(e.message)}}
$('moduleSelect').onchange=async e=>{const next=e.target.value;if(dirty&&!confirm('Tienes cambios sin guardar. ¿Cambiar de módulo y descartarlos?')){e.target.value=moduleKey;return}await loadModule(next)};$('unitSelect').onchange=e=>{unitIndex=+e.target.value;questionId=currentUnit()?.questions?.[0]?.id||'';renderReading();renderQuestionList();renderQuestionEditor()};$('searchInput').oninput=renderQuestionList;$('validateBtn').onclick=()=>showValidation(validateBank());$('saveBtn').onclick=save;$('restoreBtn').onclick=restore;$('exportBtn').onclick=exportJson;$('importInput').onchange=e=>importJson(e.target.files?.[0]);wireReading();wireQuestion();window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});boot();
})();
