// PRISMA: Panel docente: estudiantes, progreso, revision humana, investigacion, biblioteca y exportaciones.
// PRISMA: Los comentarios documentan el flujo; no cambian datos, rutas API ni comportamiento.

(()=>{
'use strict';
const TOKEN_KEY='prismaTeacherTokenV1',$=id=>document.getElementById(id);let configured=false,token=sessionStorage.getItem(TOKEN_KEY)||'',dashboard=null,currentAttempt=null,toastTimer=null,lastCreatedStudents=[];
const dims={problem:'Comprensión',solution:'Diseño',context:'Contexto',check:'Verificación'};
const eventLabels={ausencia:'Ausencia',incidencia_tecnica:'Incidencia técnica',incidencia_pedagogica:'Incidencia pedagógica',observacion:'Observación'};
// PRISMA: Escapa texto antes de insertarlo en HTML para evitar que contenido externo se interprete como codigo.
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
// PRISMA: Muestra mensajes breves en los modulos.
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000)}
// PRISMA: Realiza una solicitud autenticada al API del panel docente.
async function req(path,{method='GET',json=null}={}){const headers={};if(token)headers['X-PRISMA-Teacher-Token']=token;if(json!==null)headers['Content-Type']='application/json';const r=await fetch(path,{method,headers,body:json===null?undefined:JSON.stringify(json),cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||`Error ${r.status}`);return data}
// PRISMA: Consulta si el Clave docente ya fue configurado.
async function status(){const x=await req('/api/teacher/status');configured=!!x.configured;$('authTitle').textContent=configured?'Ingresar al panel':'Crear Clave docente';$('authHelp').textContent=configured?'Introduce la clave docente del servidor.':'El primer PIN solo puede crearse desde el equipo anfitrión.';$('confirmWrap').classList.toggle('hidden',configured);$('authBtn').textContent=configured?'Entrar':'Crear PIN y entrar'}
// PRISMA: Configura o valida el Clave docente e inicia la sesion del panel.
async function auth(e){e.preventDefault();const pin=$('teacherPin').value.trim();$('authError').textContent='';try{if(!configured){if(pin!==$('teacherPinConfirm').value.trim())throw new Error('Los PIN no coinciden.');await req('/api/teacher/setup',{method:'POST',json:{pin}});configured=true}const x=await req('/api/teacher/login',{method:'POST',json:{pin}});token=x.token;sessionStorage.setItem(TOKEN_KEY,token);showDash();await load()}catch(e){$('authError').textContent=e.message}}
// PRISMA: Cambia de la pantalla de autenticacion al panel principal.
function showDash(){$('authView').classList.add('hidden');$('dashboardView').classList.remove('hidden');$('logoutBtn').classList.remove('hidden')}
// PRISMA: Construye el resumen interpretable que consumen Hub, Ruta y modulos.
function summary(){const s=dashboard.summary||{},r=s.research||{},ins=dashboard.teacher_insights||{};const cards=[['Estudiantes',s.registered_students??s.participants??0,'registrados'],['Accesos hoy',r.today_participants||0,'sesión automática'],['Minutos hoy',r.today_minutes||0,'pantalla visible'],['Misiones',s.missions_generated||0,'generadas'],['Por revisar',ins.pending_review_count||0,'evaluaciones']];$('summaryCards').innerHTML=cards.map(([a,b,c])=>`<article class="summary-card"><strong>${esc(b)}</strong><span>${esc(a)}</span><small>${esc(c)}</small></article>`).join('');$('dashboardStatus').textContent=`Modo ${String(s.access_mode||'local').toUpperCase()} · ${s.storage||'SQLite'} ${s.db_size_mb||0} MB · ${s.document_index||'BM25'} · PRISMA ${s.app_version||'2.5.0'}`;$('attentionCount').textContent=(ins.needs_support||[]).length;$('pendingCount').textContent=ins.pending_review_count||0;$('autoDataStatus').textContent=`Hoy PRISMA detectó ${r.today_participants||0} estudiante(s), ${r.today_sessions||0} sesión(es) y ${r.today_minutes||0} minutos efectivos sin que tengas que digitarlos.`;$('libraryPill').textContent=`${s.documents_loaded||0} PDF · ${s.document_chunks||0} fragmentos`;$('libraryStatus').textContent=`Índice ${s.document_index||'BM25'} activo. Última indexación: ${dashboard.technical?.last_pdf_index_ms||0} ms.`;$('modelPill').textContent=s.model_available?`Gemma · ${s.model_provider}`:'Respaldo local'}
// PRISMA: Dibuja los promedios de las cuatro dimensiones STEM del grupo.
function mastery(){const m=dashboard.summary?.mastery_avg||{};$('masterySummary').innerHTML=Object.entries(dims).map(([k,l])=>`<div class="mastery-line"><span>${l}</span><div><i style="width:${Math.round(m[k]||0)}%"></i></div><strong>${dashboard.summary?.mastery_n?.[k]?((m[k]||0)*3/100+1).toFixed(1)+'/4':'Sin evidencia'}</strong></div>`).join('')}
// PRISMA: Muestra estudiantes que pueden necesitar acompanamiento pedagogico.
function levelFor(code,dim){const p=dashboard.participants?.find(p=>p.participant_code===code),c=p?.competence;if(!c)return 'Sin evidencia';const rows=dim?[c[dim]]:Object.values(c).filter(x=>x.tasks);if(!rows.length||!rows.every(x=>x?.tasks))return 'Sin evidencia';return (rows.reduce((n,x)=>n+x.level,0)/rows.length).toFixed(1)+'/4'}
function support(){const list=dashboard.teacher_insights?.needs_support||[];$('supportList').innerHTML=list.map(x=>`<article class="support-card ${x.weakest_score<45?'urgent':''}"><div><strong>${esc(x.participant_code)} · ${esc(x.grade)}</strong><small>${esc(x.status)} · Promedio ${levelFor(x.participant_code)}</small></div><div><span>Foco: ${esc(x.weakest_label)} ${levelFor(x.participant_code,x.weakest)}</span><small>Puede apoyar con: ${esc((x.suggested_modules||[]).join(' · '))}</small></div></article>`).join('')||'<div class="empty-good">✓ No hay alertas prioritarias con los datos actuales.</div>'}
// PRISMA: Muestra las cuentas de estudiantes ya creadas.
function studentRoster(){const rows=dashboard.student_accounts||[];$('studentRosterCount').textContent=rows.length;$('studentRosterRows').innerHTML=rows.map(x=>`<tr><td><b>${esc(x.participant_code)}</b></td><td>${esc(x.grade)}</td><td class="${x.has_progress?'roster-progress':'roster-empty'}">${x.has_progress?'Con progreso':'Aún sin actividad'}</td><td>${esc(x.last_seen||'—')}</td><td><button class="teacher-secondary" data-reset-pin="${esc(x.participant_code)}">Nuevo PIN</button></td></tr>`).join('')||'<tr><td colspan="5">Todavía no hay accesos registrados.</td></tr>';$('studentRosterRows').querySelectorAll('[data-reset-pin]').forEach(b=>b.onclick=()=>resetStudentPin(b.dataset.resetPin))}
// PRISMA: Presenta los codigos y PIN recien creados para copiarlos o imprimirlos.
function renderNewStudentAccess(){const box=$('newStudentAccessBox');box.classList.toggle('hidden',!lastCreatedStudents.length);$('newStudentAccessRows').innerHTML=lastCreatedStudents.map(x=>`<tr><td><b>${esc(x.participant_code)}</b></td><td>${esc(x.grade)}</td><td>${esc(x.pin)}</td></tr>`).join('')}
// PRISMA: Solicita al servidor la creacion masiva de accesos seudonimizados.
async function createStudents(){const btn=$('createStudentsBtn'),grade=$('studentGrade').value.trim(),prefix=$('studentPrefix').value.trim(),count=+$('studentCount').value;if(!grade){toast('Escribe el grado.');$('studentGrade').focus();return}btn.disabled=true;btn.textContent='Creando…';try{const x=await req('/api/teacher/students/create',{method:'POST',json:{grade,prefix,count}});lastCreatedStudents=x.created||[];renderNewStudentAccess();await load();toast(`${x.count||lastCreatedStudents.length} acceso(s) creado(s). Guarda o imprime los PIN ahora.`)}catch(e){toast(e.message)}finally{btn.disabled=false;btn.textContent='＋ Crear accesos'}}
// PRISMA: Regenera el PIN de un estudiante sin eliminar su trayectoria.
async function resetStudentPin(code){if(!confirm(`¿Crear un PIN nuevo para ${code}? El progreso no se borra.`))return;try{const x=await req('/api/teacher/students/reset_pin',{method:'POST',json:{participant_code:code}});lastCreatedStudents=[x];renderNewStudentAccess();toast(`PIN nuevo para ${code}: ${x.pin}`)}catch(e){toast(e.message)}}
// PRISMA: Convierte la lista de accesos en texto facil de copiar.
function studentAccessText(){return lastCreatedStudents.map(x=>`${x.participant_code} | Grado ${x.grade} | PIN ${x.pin}`).join('\n')}
// PRISMA: Copia al portapapeles los codigos y PIN recien creados.
async function copyStudentAccess(){if(!lastCreatedStudents.length)return;const text=studentAccessText();try{await navigator.clipboard.writeText(text);toast('Lista copiada.')}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Lista copiada.')}}
// PRISMA: Genera tarjetas imprimibles con codigo y PIN.
function printStudentAccess(){if(!lastCreatedStudents.length)return;const cards=lastCreatedStudents.map(x=>`<article><h2>PRISMA STEM</h2><p>Código</p><strong>${esc(x.participant_code)}</strong><p>Grado ${esc(x.grade)}</p><p>PIN</p><b>${esc(x.pin)}</b><small>No compartas tu PIN. No escribas tu nombre dentro de PRISMA.</small></article>`).join('');const w=window.open('','_blank','width=900,height=700');if(!w){toast('El navegador bloqueó la ventana de impresión.');return}w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Accesos PRISMA</title><style>body{font-family:Arial;display:grid;grid-template-columns:repeat(2,1fr);gap:16px;padding:24px}article{border:2px solid #20376d;border-radius:18px;padding:20px;break-inside:avoid}h2{margin:0 0 12px;color:#172b5c}p{margin:7px 0 2px;color:#58647c}strong,b{font-size:28px;letter-spacing:2px}small{display:block;margin-top:18px;color:#6c7484}@media print{body{padding:0}}</style></head><body>${cards}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
// PRISMA: Filtra y muestra el resumen de progreso por estudiante.
function participants(){const q=$('participantFilter').value.trim().toLowerCase();const rows=dashboard.teacher_insights?.participants||[];$('participantRows').innerHTML=rows.filter(x=>!q||`${x.participant_code} ${x.grade}`.toLowerCase().includes(q)).map(x=>`<tr><td>${esc(x.participant_code)}</td><td>${esc(x.grade)}</td><td><b>${levelFor(x.participant_code)}</b></td><td>${esc(x.weakest_label)} <small>${levelFor(x.participant_code,x.weakest)}</small></td><td>${x.mission_count||0}</td><td>${x.adaptive_passed||0}</td><td>${x.effective_minutes||0}</td><td><span class="status-chip status-${String(x.status).replace(/\s+/g,'-').toLowerCase()}">${esc(x.status)}</span></td></tr>`).join('')||'<tr><td colspan="8">Sin registros todavía.</td></tr>';const codes=new Map();for(const x of dashboard.student_accounts||[])codes.set(x.participant_code,x.grade);for(const x of rows)codes.set(x.participant_code,x.grade);$('participantCodes').innerHTML=[...codes.entries()].map(([code,grade])=>`<option value="${esc(code)}">${esc(grade)}</option>`).join('');studentRoster()}
// PRISMA: Muestra evaluaciones recientes y prioriza las que requieren revision humana.
function attempts(){const all=dashboard.recent_attempts||[],show=$('showReviewed').checked;const list=all.filter(a=>show||!a.teacher_review);$('attemptList').innerHTML=list.map((a,i)=>{const r=a.teacher_review?.rubric||((a.evaluation?.provisional||a.evaluation?.scored===false)?{}:a.evaluation?.rubric)||{},rev=a.teacher_review;return`<article class="attempt-card"><div><strong>${esc(a.participant_code)} · ${esc(a.mission_title)}</strong><small>${esc(a.created_at)} · ${esc(a.evaluation_source||'')} ${a.is_revision?'· revisión':''}</small></div><div class="attempt-rubric">${Object.entries(dims).map(([k,l])=>`<span>${l} ${r[k]?r[k]+'/4':'Pendiente'}</span>`).join('')}</div><p>${esc(a.evaluation?.feedback||'')}</p><div class="attempt-actions"><span class="info-pill">${rev?`Revisión: ${esc(rev.status)}`:'Pendiente'}</span><button class="teacher-secondary" data-attempt-id="${a.attempt_id}">Revisar</button></div></article>`}).join('')||'<div class="empty-good">✓ No hay evaluaciones pendientes.</div>';$('attemptList').querySelectorAll('[data-attempt-id]').forEach(b=>b.onclick=()=>openReview(all.find(x=>String(x.attempt_id)===String(b.dataset.attemptId))))}
// PRISMA: Muestra incidencias y eventos de fidelidad recientes.
function events(){const list=dashboard.teacher_insights?.recent_events||[];$('recentEvents').innerHTML=list.map(x=>`<article class="event-card"><strong>${esc(eventLabels[x.event_type]||x.event_type)}${x.participant_code?' · '+esc(x.participant_code):''}</strong><p>${esc(x.note||'Sin nota')}</p><small>${esc(x.created_at)}${x.minutes?` · ${x.minutes} min`:''}</small></article>`).join('')||'<div class="empty-good">✓ No hay incidencias registradas.</div>'}
// PRISMA: Refleja en pantalla la configuracion bloqueable del estudio.
function researchCfg(){const c=dashboard.research_config||{};$('protocolId').value=c.protocol_id||'';$('researchPhase').value=c.phase||'';$('researchEnabled').checked=!!c.enabled;$('libraryMissions').checked=!!c.library_missions_enabled;$('researchLockPill').textContent=c.locked?'BLOQUEADO':'Editable';for(const id of ['protocolId','researchPhase','researchEnabled','libraryMissions','lockResearch','saveResearchBtn'])$(id).disabled=!!c.locked;$('unlockResearchBtn').classList.toggle('hidden',!c.locked)}
// PRISMA: Lista instrumentos de investigacion configurados.
function instruments(){$('instrumentList').innerHTML=(dashboard.instruments||[]).map(x=>`<div class="instrument-item"><div><strong>${esc(x.title)}</strong><small>${esc(x.instrument_id)} · ${x.items} ítems · ${x.responses} respuestas</small></div><button class="teacher-secondary" data-inst="${esc(x.instrument_id)}" data-active="${x.active?'1':'0'}">${x.active?'Desactivar':'Activar'}</button></div>`).join('')||'<p class="muted">No hay instrumentos cargados.</p>';$('instrumentList').querySelectorAll('[data-inst]').forEach(b=>b.onclick=async()=>{try{await req('/api/teacher/instrument/toggle',{method:'POST',json:{instrument_id:b.dataset.inst,active:b.dataset.active!=='1'}});await load();toast('Estado actualizado.')}catch(e){toast(e.message)}})}
// PRISMA: Carga misiones disponibles para validacion por expertos.
function expertMissions(){const rows=dashboard.recent_missions||[];$('expertMission').innerHTML=rows.map(x=>`<option value="${esc(x.mission_id)}">${esc(x.participant_code)} · ${esc(x.title)}</option>`).join('')||'<option value="">Sin misiones</option>'}
// PRISMA: Muestra las ultimas mediciones tecnicas registradas.
function technical(){const t=dashboard.technical||{};$('technicalMetrics').innerHTML=Object.entries(t).map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(typeof v==='object'?JSON.stringify(v):v)}</strong></div>`).join('')}
// PRISMA: Presenta fortalezas, prioridades, acciones y estudiantes a acompanar.
function renderProgressAdvice(x){const box=$('progressAdvice'),empty=$('progressAdviceEmpty');if(!x?.ready){box.classList.add('hidden');empty.classList.remove('hidden');empty.textContent=x?.message||'Aún no hay datos suficientes para revisar el avance.';return}empty.classList.add('hidden');box.classList.remove('hidden');const strengths=(x.strengths||[]).map(v=>`<div class="advice-item good"><strong>${esc(v.label)} · ${Math.round(v.score)}%</strong><p>${esc(v.message)}</p></div>`).join('')||'<p class="muted">Aún no hay una fortaleza estable.</p>';const improve=(x.improvements||[]).map(v=>`<div class="advice-item focus"><strong>${esc(v.label)} · ${Math.round(v.score)}%</strong><p>${esc(v.message)}</p><small>Apoyo sugerido: ${esc((v.modules||[]).join(' · '))}</small></div>`).join('')||'<p class="muted">No hay una prioridad marcada.</p>';const actions=(x.actions||[]).map((v,i)=>`<li><b>${i+1}.</b> ${esc(v)}</li>`).join('');const improving=(x.improving_students||[]).map(v=>`<span class="student-progress-chip good">${esc(v.participant_code)} · +${Math.round(v.trend_delta)} pts</span>`).join('')||'<span class="muted">Aún se necesitan más intentos para calcular tendencia.</span>';const support=(x.support_students||[]).map(v=>`<span class="student-progress-chip watch">${esc(v.participant_code)} · ${esc(v.weakest_label)} ${Math.round(v.weakest_score)}%</span>`).join('')||'<span class="muted">Sin alertas altas en este momento.</span>';box.innerHTML=`<div class="progress-review-summary"><div><small>Promedio actual</small><strong>${Math.round(x.group_average||0)}%</strong></div><div><small>Tendencia reciente</small><strong>${x.trend_available?`${(x.group_trend_delta||0)>0?'+':''}${Math.round(x.group_trend_delta||0)} pts`:'Aún sin tendencia'}</strong></div><div><small>Estudiantes con datos</small><strong>${x.participants||0}</strong></div></div><div class="progress-advice-grid"><article><span class="eyebrow">LO QUE VA BIEN</span>${strengths}</article><article><span class="eyebrow">QUÉ CONVIENE FORTALECER</span>${improve}</article></div><article class="next-class-card"><span class="eyebrow">PARA LA PRÓXIMA CLASE</span><ol>${actions}</ol></article><div class="student-progress-groups"><div><strong>📈 Estudiantes con mejora reciente</strong><div class="student-chip-wrap">${improving}</div></div><div><strong>👀 Conviene acompañar</strong><div class="student-chip-wrap">${support}</div></div></div><p class="progress-note">${esc(x.note||'')}</p>`}
// PRISMA: Solicita al servidor una lectura pedagogica agregada del avance del grupo.
async function reviewProgress(){const b=$('reviewProgressBtn');b.disabled=true;b.textContent='Revisando avance…';try{const x=await req('/api/teacher/progress_review',{method:'POST',json:{}});renderProgressAdvice(x);toast(x.ready?'Lectura pedagógica actualizada.':'Todavía no hay datos suficientes.')}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='🧭 Revisar avance del grupo'}}
// PRISMA: Carga todos los datos necesarios del panel docente en una sola operacion.
async function load(){try{dashboard=await req('/api/teacher/dashboard');summary();mastery();support();participants();attempts();events();researchCfg();instruments();expertMissions();technical()}catch(e){if(/No autorizado/.test(e.message)){token='';sessionStorage.removeItem(TOKEN_KEY);location.reload()}else toast(e.message)}}
// PRISMA: Abre el formulario de revision humana para un intento concreto.
function openReview(a){if(!a)return;currentAttempt=a;$('reviewTitle').textContent=a.mission_title||'Misión';$('reviewMission').textContent=a.mission?.task||a.mission?.context||'';$('reviewAnswer').textContent=a.answer||'';const r=a.teacher_review?.rubric||((a.evaluation?.provisional||a.evaluation?.scored===false)?{}:a.evaluation?.rubric)||{};$('reviewAiRubric').innerHTML=Object.entries(dims).map(([k,l])=>`<span>${l}: <b>${r[k]?r[k]+'/4':'Pendiente'}</b></span>`).join('');$('reviewStatus').value=a.teacher_review?.status||'approved';$('reviewProblem').value=a.teacher_review?.rubric?.problem||r.problem||'';$('reviewSolution').value=a.teacher_review?.rubric?.solution||r.solution||'';$('reviewContext').value=a.teacher_review?.rubric?.context||r.context||'';$('reviewCheck').value=a.teacher_review?.rubric?.check||r.check||'';$('reviewNote').value=a.teacher_review?.note||'';$('reviewModal').classList.remove('hidden')}
// PRISMA: Guarda el ajuste o aprobacion docente conservando la evaluacion original de IA.
async function saveReview(e){e.preventDefault();if(!currentAttempt)return;const status=$('reviewStatus').value,rubric={problem:+$('reviewProblem').value,solution:+$('reviewSolution').value,context:+$('reviewContext').value,check:+$('reviewCheck').value};try{await req('/api/teacher/review',{method:'POST',json:{attempt_id:currentAttempt.attempt_id,status,rubric,note:$('reviewNote').value}});$('reviewModal').classList.add('hidden');await load();toast('Revisión guardada. La orientación original se conserva.')}catch(e){toast(e.message)}}
// PRISMA: Guarda protocolo, fase y opciones del modo investigacion.
async function saveResearch(){try{const out=await req('/api/teacher/research/config',{method:'POST',json:{enabled:$('researchEnabled').checked,protocol_id:$('protocolId').value,phase:$('researchPhase').value,library_missions_enabled:$('libraryMissions').checked,lock:$('lockResearch').checked}});dashboard.research_config=out.config;researchCfg();toast('Configuración guardada.')}catch(e){toast(e.message)}}
// PRISMA: Desbloquea la configuracion del estudio solo tras confirmacion explicita.
async function unlockResearch(){const confirmText=prompt('Escribe DESBLOQUEAR para permitir cambios al protocolo.');if(!confirmText)return;try{const out=await req('/api/teacher/research/unlock',{method:'POST',json:{confirm:confirmText}});dashboard.research_config=out.config;researchCfg();toast('Configuración desbloqueada.')}catch(e){toast(e.message)}}
// PRISMA: Carga un PDF curricular y solicita su indexacion BM25 local.
async function uploadPdf(){const f=$('teacherPdfInput').files?.[0];if(!f){toast('Selecciona un PDF.');return}if(f.size>(window.PRISMA_ONLINE_CONFIG?.backend==='apps-script'?3:20)*1024*1024){toast('El PDF supera el límite de esta edición (3 MB en Apps Script).');return}const data=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(f)});try{const x=await req('/api/upload_pdf',{method:'POST',json:{filename:f.name,data_base64:data}});toast(`PDF indexado con BM25 · ${x.index_ms||0} ms`);await load()}catch(e){toast(e.message)}}
// PRISMA: Vacia la biblioteca curricular local tras confirmacion del docente.
async function clearDocs(){if(!confirm('¿Vaciar la biblioteca curricular local?'))return;try{await req('/api/clear_docs',{method:'POST',json:{}});await load();toast('Biblioteca vaciada.')}catch(e){toast(e.message)}}
// PRISMA: Registra manualmente solo excepciones: ausencia, incidencia u observacion.
async function fidelity(){const note=$('fidelityNote').value.trim(),type=$('fidelityType').value;if(type==='observacion'&&!note){toast('Escribe una nota breve para la observación.');return}try{await req('/api/teacher/research/log_event',{method:'POST',json:{participant_code:$('fidelityCode').value,event_type:type,minutes:+$('fidelityMinutes').value,note}});$('fidelityNote').value='';$('fidelityMinutes').value='0';await load();toast('Excepción guardada.')}catch(e){toast(e.message)}}
// PRISMA: Guarda una valoracion de experto sobre una mision STEM.
async function expert(){const opt=$('expertMission').selectedOptions[0];try{await req('/api/teacher/expert_validation',{method:'POST',json:{mission_id:$('expertMission').value,mission_title:opt?.textContent||'',evaluator_code:$('expertCode').value,territorial:+$('expertTerritorial').value,clarity:+$('expertClarity').value,stem_alignment:+$('expertStem').value,problem_solving:+$('expertProblem').value,scaffolding:+$('expertScaffolding').value,ethics:+$('expertEthics').value,note:$('expertNote').value}});$('expertNote').value='';await load();toast('Validación experta guardada.')}catch(e){toast(e.message)}}
// PRISMA: Valida y carga un instrumento de investigacion definido en JSON.
async function uploadInstrument(){let def;try{def=JSON.parse($('instrumentJson').value)}catch{toast('JSON inválido.');return}try{await req('/api/teacher/instrument/upload',{method:'POST',json:{definition:def,active:$('instrumentActive').checked}});$('instrumentJson').value='';await load();toast('Instrumento cargado.')}catch(e){toast(e.message)}}
// PRISMA: Ejecuta mediciones de respuesta del servidor y, opcionalmente, de Gemma.
async function benchmark(){const btn=$('benchmarkBtn');btn.disabled=true;$('benchmarkResult').textContent='Midiendo…';try{const times=[];for(let i=0;i<8;i++){const t=performance.now();await fetch('/api/health',{cache:'no-store'});times.push(performance.now()-t)}const x=await req('/api/teacher/benchmark',{method:'POST',json:{loops:60,include_ai:$('includeAiBenchmark').checked,http_client_ms:times}});$('benchmarkResult').textContent=JSON.stringify(x.result,null,2);await load()}catch(e){$('benchmarkResult').textContent=e.message}finally{btn.disabled=false}}
// PRISMA: Descarga de forma autenticada un archivo generado por el servidor.
async function downloadBlob(path,filename){const r=await fetch(path,{headers:{'X-PRISMA-Teacher-Token':token},cache:'no-store'});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.detail||'No se pudo descargar.')}const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
// PRISMA: Descarga el paquete ZIP completo de datos de investigacion.
async function downloadPack(){const b=$('downloadPackBtn');b.disabled=true;b.textContent='Preparando datos…';try{await downloadBlob('/api/teacher/research_pack.zip','PRISMA_DATOS_INVESTIGACION_v248.zip');toast('Paquete descargado. Empieza por INFORME_DOCENTE.html o prisma_overview_v248.csv.')}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='📦 Descargar paquete de investigación'}}
// PRISMA: Abre el informe docente HTML o lo descarga si el navegador bloquea la ventana.
async function openReport(){try{const r=await fetch('/api/teacher/report.html',{headers:{'X-PRISMA-Teacher-Token':token},cache:'no-store'});if(!r.ok)throw new Error('No se pudo generar el informe.');const b=await r.blob(),u=URL.createObjectURL(b),w=window.open(u,'_blank');if(!w)await downloadBlob('/api/teacher/report.html','INFORME_DOCENTE_PRISMA.html');setTimeout(()=>URL.revokeObjectURL(u),60000)}catch(e){toast(e.message)}}
// PRISMA: Descarga un CSV especializado del panel docente.
function exportCsv(kind){downloadBlob(`/api/teacher/export.csv?kind=${encodeURIComponent(kind)}&t=${Date.now()}`,`prisma_${kind}_v248.csv`).catch(e=>toast(e.message))}
// PRISMA: Cierra la sesion de estudiante y limpia datos temporales de la pestana.
async function logout(){try{await req('/api/teacher/logout',{method:'POST',json:{}})}catch{}sessionStorage.removeItem(TOKEN_KEY);location.reload()}
$('authForm').onsubmit=auth;$('logoutBtn').onclick=logout;$('refreshBtn').onclick=load;$('createStudentsBtn').onclick=createStudents;$('copyStudentAccessBtn').onclick=copyStudentAccess;$('printStudentAccessBtn').onclick=printStudentAccess;$('participantFilter').oninput=participants;$('showReviewed').onchange=attempts;$('saveResearchBtn').onclick=saveResearch;$('unlockResearchBtn').onclick=unlockResearch;$('teacherPdfInput').onchange=()=>{$('teacherPdfName').textContent=$('teacherPdfInput').files?.[0]?.name||'Máximo 20 MB'};$('uploadPdfBtn').onclick=uploadPdf;$('clearLibraryBtn').onclick=clearDocs;$('saveFidelityBtn').onclick=fidelity;$('saveExpertBtn').onclick=expert;$('uploadInstrumentBtn').onclick=uploadInstrument;$('benchmarkBtn').onclick=benchmark;$('reviewForm').onsubmit=saveReview;$('closeReview').onclick=()=>$('reviewModal').classList.add('hidden');$('downloadPackBtn').onclick=downloadPack;$('openReportBtn').onclick=openReport;$('goAttentionBtn').onclick=()=>$('attentionSection').scrollIntoView({behavior:'smooth'});$('reviewProgressBtn').onclick=reviewProgress;document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportCsv(b.dataset.export));
(async()=>{try{await status();if(token){showDash();await load()}}catch(e){$('authError').textContent=e.message}})();
})();
