const DIMS=['problem','solution','context','check'];
function code_(s){s=String(s||'').trim();need_(/^[A-Za-z0-9_-]{1,48}$/.test(s),'Código inválido.');return s;}
function key_(s){return hash_(String(s));}
function studentSnapshot_(d,c){return {state:d.states[key_(c)]||null,modules:Object.fromEntries(Object.values(d.modules).filter(m=>m.participant_code===c).map(m=>[m.module_key,m.state])),policy:d.policy};}
function person_(d,c){return d.people[key_(c)]||{};}
function eligible_(m){return m.consent==='granted'&&(m.role!=='student'||m.assent==='granted')&&!m.withdrawn;}
function frozen_(d){return d.cohorts.some(x=>x.phase==='intervention');}
function authenticate_(d,q){const t=d.tokens[key_(q.teacher_token||q.student_token||'')];need_(t&&t.expires>Date.now(),'No autorizado. Vuelve a iniciar sesión.',401);if(t.role==='student')need_(d.accounts[key_(t.code)],'Acceso retirado.',401);return t;}
function loginLimit_(name){const c=CacheService.getScriptCache(),k='login-'+key_(name),n=Number(c.get(k)||0);need_(n<12,'Demasiados intentos. Espera un minuto.',429);c.put(k,String(n+1),60);}
function token_(d,role,code){const token=id_()+id_();for(const k of Object.keys(d.tokens))if(d.tokens[k].expires<Date.now())delete d.tokens[k];d.tokens[key_(token)]={role,code:code||'',expires:Date.now()+8*3600000};return {token,participant_code:code||'',expires_in:28800};}
function competence_(s){const out={};for(const k of DIMS){const rows=Object.values(s.taskEvidence||{}).filter(e=>!e.provisional&&Number.isInteger(e.rubric&&e.rubric[k])&&e.rubric[k]>=1&&e.rubric[k]<=4);out[k]={level:rows.length?rows.reduce((n,e)=>n+e.rubric[k],0)/rows.length:null,tasks:rows.length,human:rows.filter(e=>e.source==='docente').length};}return out;}
function mergeState_(d,c,incoming){const old=d.states[key_(c)]||{};incoming=clone_(incoming||{});incoming.taskEvidence=incoming.taskEvidence||{};for(const [k,e]of Object.entries(old.taskEvidence||{}))if(e.source==='docente')incoming.taskEvidence[k]=e;for(const [k,e]of Object.entries(incoming.taskEvidence))if(!old.taskEvidence||old.taskEvidence[k]?.source!=='docente'){e.provisional=true;if(e.source==='docente')e.source='pendiente';}incoming.competence=competence_(incoming);incoming.mastery=Object.fromEntries(DIMS.map(k=>[k,incoming.competence[k].level===null?0:(incoming.competence[k].level-1)*100/3]));d.states[key_(c)]=incoming;return incoming;}
function advice_(s){s=String(s||'').toLowerCase();if(/verific|comprob|revis/.test(s))return PLANS.check.action;if(/justif|porque|context/.test(s))return PLANS.context.action;if(/soluci|pasos|diseñ/.test(s))return PLANS.solution.action;return PLANS.problem.action;}
function mission_(d,p,c){
 const used=new Set(d.missions.filter(x=>x.participant_code===c).map(x=>x.id));let choices=MISSIONS.filter(x=>!used.has(x.id));need_(choices.length,'Ya recibiste los 40 retos. Revisa tus respuestas; no se repetirán automáticamente.',409);
 const matching=choices.filter(x=>(x.module_tags||[]).includes(p.application_module));if(matching.length)choices=matching;
 const m=clone_(choices[Math.floor(Math.random()*choices.length)]),f=p.focus||{},level=['basico','intermedio','avanzado'].includes(f.complexity)?f.complexity:'basico';
 const support=['guiado','equilibrado','autonomo'].includes(p.support_level)?p.support_level:(f.mode==='extension'?'autonomo':level==='basico'?'guiado':'equilibrado');
 const matrix={basico:'Compara dos opciones con los datos disponibles. Elige una, justifica con un dato y comprueba una condición.',intermedio:'Compara dos opciones y sus restricciones. Cambia por escrito un dato del caso y comprueba si cambia tu decisión.',avanzado:'Compara dos soluciones con criterios en conflicto. Analiza por escrito dos cambios de datos y argumenta límites y mejoras.'};
 const steps={guiado:DIMS.map(k=>PLANS[k].action),equilibrado:['Explica tu estrategia y compara alternativas.','Justifica y comprueba con los datos.'],autonomo:['Organiza tu respuesta y comprueba sus límites.']};
 Object.assign(m,{mission_id:'ONLINE-'+id_(),participant_code:c,grade:d.accounts[key_(c)].grade,complexity:level,support_level:support,steps:steps[support],task:m.task+'\n'+matrix[level],generated_by:'banco-predisenado',focus_dimension:DIMS.includes(f.dimension)?f.dimension:'problem',bank_remaining:39-used.size,created_at:now_(),evidence_key:m.id,purpose:p.parent_mission_id?'transfer':f.mode==='diagnostic'?'diagnostic':'practice',parent_mission_id:p.parent_mission_id||'',policy_version:d.policy.version,application_module:p.application_module||'',curriculum_sources:[],story:'Reto '+(used.size+1)+' de 40.',adaptation_reason:'Caso aleatorio sin repetición; complejidad y ayudas según tu trayectoria.',quality_check:'structural-pass; semantic-expert-review-pending'});
 m.raw_text=['TÍTULO: '+m.title,'CONTEXTO: '+m.context,'RETO: '+m.task,...m.steps.map((x,i)=>'PASO '+(i+1)+': '+x)].join('\n');d.missions.push(m);return {mission:m,source:'banco-predisenado',remaining:m.bank_remaining};
}
function evaluate_(d,p,c){
 const m=d.missions.find(x=>x.mission_id===(p.mission_id||p.mission?.mission_id)&&x.participant_code===c);need_(m,'El reto no pertenece a tu cuenta.',403);need_(typeof p.answer==='string'&&p.answer.trim()&&p.answer.length<=30000,'Escribe tu razonamiento (máximo 30.000 caracteres).');
 const dim=m.focus_dimension,plan=PLANS[dim],result={attempt_id:d.attempts.length?Math.max(...d.attempts.map(a=>a.attempt_id))+1:1,rubric:{problem:1,solution:1,context:1,check:1},weakest:dim,provisional:true,scored:false,model_used:false,evaluation_source:'guia-predeterminada',feedback:'Respuesta guardada. La valoración de las cuatro habilidades queda pendiente del docente.',strengths:['Conserva las ideas relacionadas con el enunciado.'],weaknesses:['Esta guía no determina tu nivel.'],improvements:[plan.action],learning_goal:plan.label,learning_route:[plan.action,'Revisa el módulo recomendado y mejora esta misma respuesta.'],micro_challenge:plan.action,success_criterion:plan.success,rubric_details:{},app_version:APP_VERSION};
 d.attempts.push({attempt_id:result.attempt_id,participant_code:c,grade:d.accounts[key_(c)].grade,mission_id:m.mission_id,mission_title:m.title,mission:clone_(m),answer:p.answer,evaluation:clone_(result),evaluation_source:result.evaluation_source,session_id:p.session_id||'',duration_ms:Math.max(0,Number(p.duration_ms)||0),process:p.process||{},is_revision:!!p.is_revision,created_at:now_()});return result;
}
function route_(d,q){
 const path=String(q.path||''),p=q.payload||{},params=q.query||{},get=q.method==='GET';need_(['GET','POST'].includes(q.method),'Método inválido.');
 if(path==='/api/health'||path==='/health')return {status:'ok',offline:false,access_mode:'online',student_auth_required:true,model_available:false,storage:'google-apps-script-sheets',app_version:APP_VERSION,documents_loaded:d.documents.length,document_chunks:d.documents.reduce((n,x)=>n+x.chunks.length,0),document_index:'BM25',research:d.config};
 if(path==='/api/adaptive_policy')return d.policy;
 if(path==='/api/research/config')return d.config;
 if(path==='/api/teacher/status')return {configured:!!props_().getProperty('PRISMA_TEACHER_HASH'),setup_local_only:true};
 if(path==='/api/teacher/setup')fail_('Configura la contraseña en las propiedades privadas de Apps Script.',403);
 if(path==='/api/teacher/login'){need_(!get,'Método inválido.');loginLimit_('teacher');need_(hash_(props_().getProperty('PRISMA_AUTH_SALT')+String(p.pin))===props_().getProperty('PRISMA_TEACHER_HASH'),'Clave incorrecta.',401);return token_(d,'teacher');}
 if(path==='/api/student/login'){need_(!get,'Método inválido.');const c=code_(p.participant_code);loginLimit_(c);const a=d.accounts[key_(c)];need_(a&&a.pin_hash===hash_(props_().getProperty('PRISMA_AUTH_SALT')+String(p.pin_hash)),'Código o PIN incorrecto.',401);return {...token_(d,'student',c),grade:a.grade,snapshot:studentSnapshot_(d,c)};}
 const auth=authenticate_(d,q),teacher=auth.role==='teacher';
 if(path.startsWith('/api/teacher/')||['/api/upload_pdf','/api/clear_docs','/api/clear_documents'].includes(path))need_(teacher,'Acceso docente requerido.',403);
 if(path.endsWith('/logout')){need_(!get,'Método inválido.');delete d.tokens[key_(q.teacher_token||q.student_token)];return {ok:true};}
 let c=teacher?String(p.participant_code||params.participant_code||''):auth.code;
 if(!teacher)need_(!(p.participant_code||params.participant_code)||(p.participant_code||params.participant_code)===c,'No puedes acceder a otra cuenta.',403);
 if(path==='/api/student/snapshot'){need_(get&&!teacher,'Acceso estudiante requerido.',403);return studentSnapshot_(d,c);}
 const helpers=/^\/api\/(generate|evaluate_stem|prismi_tip|ask_document)/.test(path);
 if(helpers&&eligible_(person_(d,c))&&d.assignments.some(a=>a.subject===c&&a.instrument==='IM-3'&&a.status==='assigned'))fail_('Completa primero IM-3 sin ayudas.',423);
 const protectedPaths=['/api/teacher/question_bank/save','/api/teacher/question_bank/restore','/api/teacher/instrument/upload','/api/upload_pdf','/api/clear_docs','/api/clear_documents','/api/teacher/research/config','/api/teacher/research/unlock','/api/teacher/adaptive_policy'];
 if(!get&&frozen_(d)&&protectedPaths.includes(path))fail_('La intervención está congelada. Conserva su versión.',423);
 if(path.startsWith('/api/teacher/study/')||path.startsWith('/api/study/'))return study_(d,path,p,c,teacher,get);
 if(path==='/api/teacher/dashboard')return dashboard_(d);
 if(path==='/api/teacher/students/create'){
  need_(!get,'Método inválido.');const count=Number(p.count),prefix=String(p.prefix||'EST').toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,16)||'EST';need_(Number.isInteger(count)&&count>=1&&count<=100&&String(p.grade||'').trim(),'Indica grado y cantidad entre 1 y 100.');const created=[];
  for(let i=0,n=1;i<count;n++){const code=prefix+'-'+String(n).padStart(3,'0');if(d.accounts[key_(code)])continue;const pin=String(100000+Math.floor(Math.random()*900000));d.accounts[key_(code)]={participant_code:code,grade:String(p.grade).slice(0,18),pin_hash:hash_(props_().getProperty('PRISMA_AUTH_SALT')+hash_('PRISMA-LOCAL:'+code+':'+pin)),created_at:now_()};created.push({participant_code:code,grade:p.grade,pin});i++;}return {created,count:created.length};
 }
 if(path==='/api/teacher/students/reset_pin'){need_(!get,'Método inválido.');const a=d.accounts[key_(p.participant_code)];need_(a,'Cuenta no encontrada.',404);const pin=String(100000+Math.floor(Math.random()*900000));a.pin_hash=hash_(props_().getProperty('PRISMA_AUTH_SALT')+hash_('PRISMA-LOCAL:'+a.participant_code+':'+pin));for(const k of Object.keys(d.tokens))if(d.tokens[k].code===a.participant_code)delete d.tokens[k];return {participant_code:a.participant_code,grade:a.grade,pin};}
 if(path==='/api/adaptive_state'){if(get)return {state:d.states[key_(c)]||null};return {ok:true,state:mergeState_(d,c,p.state)};}
 if(path==='/api/module_state'){const k=key_(c+'|'+(p.module_key||params.module_key));if(get)return {state:d.modules[k]?.state||null};need_(p.state&&typeof p.state==='object','Estado inválido.');d.modules[k]={participant_code:c,module_key:p.module_key,state:p.state,updated_at:now_()};return {ok:true};}
 if(path==='/api/learner_profile'){if(get)return {context:d.profiles[key_(c)]||{}};d.profiles[key_(c)]=p.context||{};return {ok:true};}
 if(path.startsWith('/api/generate_mission')){need_(!get,'Método inválido.');return mission_(d,p,c);}
 if(path.startsWith('/api/evaluate_stem')){need_(!get,'Método inválido.');return evaluate_(d,p,c);}
 if(path==='/api/prismi_tip')return {tip:advice_(p.focus),source:'guia-predeterminada'};
 if(path==='/api/generate'||path==='/api/generate_stream')return {answer:advice_(p.prompt),source:'guia-predeterminada'};
 if(path.startsWith('/api/research/session/')){need_(!get,'Método inválido.');if(path.endsWith('/start')){const old=d.sessions[key_(p.session_id||'')];if(old&&old.participant_code===c&&!old.ended_at)return {session_id:old.session_id};const sid=id_();d.sessions[key_(sid)]={session_id:sid,participant_code:c,started_at:now_(),effective_ms:0,last_seen:now_()};return {session_id:sid};}const s=d.sessions[key_(p.session_id)];need_(s&&s.participant_code===c,'Sesión no encontrada.',404);s.effective_ms+=Math.max(0,Math.min(120000,Number(p.visible_ms)||0));s.last_seen=now_();if(path.endsWith('/end'))s.ended_at=now_();return {ok:true};}
 if(['/api/research/event','/api/interaction','/api/teacher/research/log_event','/api/teacher/expert_validation'].includes(path)){need_(!get,'Método inválido.');if(!p.event_id||!d.events.some(e=>e.event_id===p.event_id&&e.participant_code===c))d.events.push({...p,participant_code:c,event_type:p.event_type||path.split('/').pop(),created_at:now_()});return {ok:true};}
 if(path==='/api/teacher/review'){need_(!get,'Método inválido.');return review_(d,p);}
 if(path==='/api/teacher/adaptive_policy'){need_(!get&&!d.config.locked,'El protocolo está bloqueado.',423);for(const [k,lo,hi]of [['minTasks',2,12],['minSessions',2,12],['minIndependent',1,12],['minTransfer',1,6],['minLevel',3,4]])need_(Number.isInteger(p[k])&&p[k]>=lo&&p[k]<=hi,'Criterio inválido: '+k);need_(Math.max(p.minSessions,p.minIndependent,p.minTransfer)<=p.minTasks,'Los mínimos parciales superan el número de retos.');d.policy=Object.fromEntries(['minTasks','minSessions','minIndependent','minTransfer','minLevel'].map(k=>[k,p[k]]));d.policy.version='3.2-'+hash_(JSON.stringify(d.policy)).slice(0,10);return d.policy;}
 if(path==='/api/teacher/research/config'){need_(!get&&!d.config.locked,'Protocolo bloqueado.',423);d.config={enabled:!!p.enabled,protocol_id:String(p.protocol_id||''),phase:String(p.phase||''),library_missions_enabled:!!p.library_missions_enabled,locked:!!p.lock};return {config:d.config};}
 if(path==='/api/teacher/research/unlock'){need_(!get&&p.confirm==='DESBLOQUEAR','Escribe DESBLOQUEAR.');d.config.locked=false;return {config:d.config};}
 if(path==='/api/teacher/progress_review'){const dash=dashboard_(d),parts=dash.participants.filter(p=>DIMS.some(k=>p.competence[k].tasks)),values=parts.flatMap(p=>DIMS.filter(k=>p.competence[k].tasks).map(k=>p.mastery[k]));return {ready:!!values.length,participants:parts.length,group_average:values.length?values.reduce((a,b)=>a+b,0)/values.length:null,trend_available:false,strengths:[],improvements:[],support_students:dash.teacher_insights.needs_support,actions:['Revisa las respuestas pendientes y registra evidencia con la rúbrica.','Compara varios retos y sesiones antes de concluir dominio.'],message:'Se requiere evidencia revisada por el docente.'};}
 if(path.startsWith('/api/teacher/question_bank')||path==='/api/question_bank')return banks_(d,path,p,params,get,teacher);
 if(path.startsWith('/api/teacher/instrument/')||path.startsWith('/api/instruments/'))return instruments_(d,path,p,c,get);
 if(path.startsWith('/api/ask_document')||path==='/api/upload_pdf'||path==='/api/clear_docs'||path==='/api/clear_documents')return documents_(d,path,p,get);
 if(['/api/teacher/export.csv','/api/teacher/report.html','/api/teacher/research_pack.zip'].includes(path))return export_(d,path,params.kind||'overview');
 if(path==='/api/teacher/benchmark'){need_(!get,'Método inválido.');const result={platform:'Google Apps Script',model_used:false,measured_at:now_(),http_client_ms:p.http_client_ms||[],notice:'Latencias medidas desde el cliente; sin métricas inventadas de CPU o memoria.'};(d.benchmarks||(d.benchmarks=[])).push(result);return {result};}
 fail_('Operación no encontrada: '+path,404);
}
function review_(d,p){const a=d.attempts.find(x=>String(x.attempt_id)===String(p.attempt_id));need_(a,'Respuesta no encontrada.',404);need_(['approved','adjusted','needs_followup','ai_imprecise','possible_bias'].includes(p.status),'Estado de revisión inválido.');const r=p.rubric||{};for(const k of DIMS)need_(Number.isInteger(r[k])&&r[k]>=1&&r[k]<=4,'La rúbrica requiere cuatro valores entre 1 y 4.');const rev={attempt_id:a.attempt_id,status:p.status,rubric:r,note:String(p.note||'').slice(0,4000),created_at:now_()};d.reviews.push(rev);const s=d.states[key_(a.participant_code)]||{},m=a.mission;s.taskEvidence=s.taskEvidence||{};s.taskEvidence[m.mission_id]={...s.taskEvidence[m.mission_id],missionId:m.mission_id,evidenceKey:m.evidence_key,rubric:r,source:'docente',provisional:!['approved','adjusted'].includes(p.status),sessionId:a.session_id,purpose:m.purpose,complexity:m.complexity,supportLevel:m.support_level,assisted:a.process.support!=='none',assistanceKnown:!!a.process.support,revision:a.is_revision,parentMissionId:m.parent_mission_id,at:Date.now(),updatedAt:Date.now()};d.states[key_(a.participant_code)]=s;mergeState_(d,a.participant_code,s);return {ok:true};}
