function record_(d,kind,iid,subject,occasion,payload){const id=id_();d.records.push({id,kind,instrument:iid,subject,occasion,version:CATALOG[iid]?.version||'3.0',payload:JSON.stringify(payload),created_at:now_()});return {ok:true,id};}
function answers_(doc,answers,form){need_(answers&&typeof answers==='object'&&!Array.isArray(answers),'Respuestas inválidas.');const items=doc.id==='IM-3'?doc.forms[form].items:doc.items,out={};for(const i of items){let v=answers[i.id];if(v===null||v===undefined||v===''){out[i.id]=null;continue;}if(i.type==='text')need_(typeof v==='string'&&v.length<=10000,'Respuesta demasiado larga.');else need_(i.values.includes(v),'Respuesta fuera de escala: '+i.id);out[i.id]=v;}return out;}
function manifest_(d){return {app_version:APP_VERSION,release:RELEASE_HASH,catalog:hash_(JSON.stringify(CATALOG)),missions:hash_(JSON.stringify(MISSIONS)),banks:hash_(JSON.stringify(d.banks)),policy:d.policy};}
function studyData_(d){return {study_people:Object.entries(d.people).map(([,m])=>({code:m.code,metadata:JSON.stringify(m),updated_at:m.updated_at})),study_records:d.records.map(r=>({...r,included_in_research:r.kind==='application'?eligible_(person_(d,r.subject)):null})),study_assignments:d.assignments,study_scores:d.scores,study_releases:Object.values(d.releases),study_cohorts:d.cohorts};}
function study_(d,path,p,c,teacher,get){
 const action=path.split('/').pop();
 if(get&&teacher){if(action==='catalog')return CATALOG;if(action==='data')return studyData_(d);if(action==='summary')return summary_(d);if(action==='integrity')return {cohorts:d.cohorts.map(x=>({id:x.id,phase:x.phase,matches:x.manifest===JSON.stringify(manifest_(d))}))};}
 if(get&&action==='assignments')return {assignments:eligible_(person_(d,c))?d.assignments.filter(a=>a.subject===c&&a.status==='assigned').map(a=>{const doc=CATALOG[a.instrument];return {...a,title:doc.title,items:a.instrument==='IM-3'?doc.forms[a.form].items:doc.items,context:a.instrument==='IM-3'?doc.forms[a.form].context:[]};}):[]};
 if(action==='draft'){need_(!teacher,'Acceso de estudiante requerido.');const kind=p.kind||'adaptive';need_(['adaptive','learning'].includes(kind),'Tipo inválido.');const k=key_(c+'|'+kind);if(get)return {draft:d.drafts[k]?.payload||null};need_(p.draft&&typeof p.draft==='object'&&JSON.stringify(p.draft).length<=150000,'Borrador inválido.');const old=d.drafts[k]?.payload;if(old&&old.updatedAt>p.draft.updatedAt)return {ok:true,stale:true};if(old&&kind==='adaptive'&&old.mission?.mission_id!==p.draft.mission?.mission_id)record_(d,'draft_archive','',c,'',old);d.drafts[k]={subject:c,kind,payload:p.draft};return {ok:true};}
 need_(!get,'Operación no encontrada.',404);
 if(action==='incident')return record_(d,'incident','',teacher?String(p.subject||''):c,'',{note:String(p.note||'').slice(0,2000),category:String(p.category||'').slice(0,80),mission_id:String(p.mission_id||'')});
 if(action==='application_draft'||action==='respond'){
  const subject=teacher?code_(p.subject):c,a=d.assignments.find(a=>a.id===p.assignment_id&&a.subject===subject);need_(a&&a.status==='assigned'&&eligible_(person_(d,subject)),'Aplicación no disponible o ya enviada.');const k=key_(subject+'|instrument:'+a.id);
  if(action==='application_draft'){if(p.load)return {draft:d.drafts[k]?.payload||null};need_(p.draft&&typeof p.draft==='object'&&JSON.stringify(p.draft).length<=150000,'Borrador inválido.');d.drafts[k]={subject,kind:'instrument:'+a.id,payload:p.draft};return {ok:true};}
  const out=record_(d,'application',a.instrument,subject,a.occasion,{assignment_id:a.id,form:a.form,answers:answers_(CATALOG[a.instrument],p.answers,a.form),metadata:person_(d,subject),duration_ms:Math.max(0,Math.min(86400000,Number(p.duration_ms)||0)),medium:p.medium||'digital',notes:String(p.notes||'').slice(0,3000),definition:CATALOG[a.instrument]});a.status='completed';delete d.drafts[k];return out;
 }
 need_(teacher,'Acceso docente requerido.',403);
 if(action==='enroll'){
  const subject=code_(p.code),m=p.metadata;need_(m&&typeof m==='object','Falta caracterización.');const allowed=['role','institution','course','teacher','cohort','condition','phase','grade','consent','assent','withdrawn','retention_until','consent_reference','area','experience_years','age_band','digital_skills','device','connectivity'];const clean=Object.fromEntries(allowed.filter(k=>k in m).map(k=>[k,m[k]]));
  need_(['student','teacher','expert','observer'].includes(clean.role)&&['experimental','comparison','pilot','none'].includes(clean.condition)&&['pilot','intervention','none'].includes(clean.phase),'Rol, condición o fase inválidos.');for(const k of ['consent','assent'])need_(['pending','granted','declined'].includes(clean[k]),'Indica consentimiento y asentimiento.');need_(clean.consent!=='granted'||String(clean.consent_reference||'').trim(),'Falta referencia de autorización.');const old=person_(d,subject);need_(!(old.phase==='pilot'&&clean.phase==='intervention'),'No mezcles participantes del pilotaje con la intervención.');if(old.cohort&&frozen_(d))need_(['cohort','course','condition','institution','phase'].every(k=>old[k]===clean[k]),'La asignación del estudio está congelada.');d.people[key_(subject)]={...clean,code:subject,updated_at:now_()};return record_(d,'enrollment','',subject,'',{before:old,after:clean});
 }
 if(action==='assign'){
  const subject=code_(p.subject),iid=p.instrument,m=person_(d,subject),occasion=p.occasion,valid={'IM-1':['baseline'],'IM-2':['post'],'IM-3':['pre','post'],'IM-4':['pre','post']};need_(valid[iid]&&valid[iid].includes(occasion),'Instrumento o momento inválidos.');need_(eligible_(m)&&m.cohort,'Se requiere autorización documentada y cohorte.');need_(iid==='IM-4'?m.role==='teacher':m.role==='student','Instrumento no corresponde al rol.');need_(iid!=='IM-2'||m.condition==='experimental'||m.phase==='pilot','IM-2 corresponde al grupo experimental o pilotaje.');let form='';
  if(iid==='IM-3'){form=p.form;need_(['A','B'].includes(form),'Indica forma A o B.');const opposite=d.assignments.find(a=>a.subject===subject&&a.instrument===iid&&a.occasion!==occasion&&a.cohort===m.cohort);need_(!opposite||opposite.form!==form,'Usa la otra forma en la otra ocasión.');const same=d.assignments.find(a=>a.instrument===iid&&a.occasion===occasion&&a.cohort===m.cohort&&person_(d,a.subject).course===m.course);need_(!same||same.form===form,'Respeta la secuencia A/B común del curso.');}
  need_(!d.assignments.some(a=>a.subject===subject&&a.instrument===iid&&a.occasion===occasion&&a.cohort===m.cohort),'Esta aplicación ya fue asignada.');if(m.phase==='intervention')need_(d.releases[iid]?.status==='validated'&&d.cohorts.some(x=>x.id===m.cohort&&x.phase==='intervention'),'Valida instrumentos y congela la cohorte antes de aplicar.');const id=id_();d.assignments.push({id,subject,instrument:iid,version:CATALOG[iid].version,occasion,form,cohort:m.cohort,status:'assigned',created_at:now_()});return {ok:true,id};
 }
 if(action==='content'){
  const doc=CATALOG[p.instrument];need_(doc,'Instrumento inválido.');const evaluator=code_(p.evaluator),clean={};need_(String(p.expert_profile||'').trim(),'Registra el perfil del juez.');for(const u of doc.validation_units){const row=(p.ratings||{})[u.id]||{},vals={};for(const attr of ['clarity','relevance','representativeness',...(u.equivalence?['equivalence']:[])]){const v=row[attr];need_([1,2,3,4,5,'N/A'].includes(v),'Valora cada atributo con 1–5 o N/A.');need_(![1,2,3,'N/A'].includes(v)||String(row.note||'').trim(),'Justifica N/A y valores 1–3.');vals[attr]=v;}clean[u.id]={...vals,note:String(row.note||'').slice(0,3000)};}return record_(d,'content',doc.id,evaluator,String(p.round||'1'),{ratings:clean,expert_profile:p.expert_profile});
 }
 if(action==='observe'){need_(['VP-1','VP-2'].includes(p.instrument),'Selecciona VP-1 o VP-2.');const evaluator=code_(p.evaluator),ans=answers_(CATALOG[p.instrument],p.answers),notes=p.notes||{};for(const [k,v]of Object.entries(ans))if(p.instrument==='VP-1'&&[1,2,3,'N/A'].includes(v))need_(String(notes[k]||'').trim(),'Justifica N/A y puntuaciones 1–3.');return record_(d,p.instrument==='VP-1'?'prototype':'pilot',p.instrument,evaluator,String(p.occasion||''),{answers:ans,notes,context:p.context||{},technical:p.technical||{},incidents:p.incidents||[],recommendation:p.recommendation||''});}
 if(action==='score'){need_(d.records.some(r=>r.id===p.response_id&&r.kind==='application'&&r.instrument==='IM-3'),'Respuesta IM-3 no encontrada.');const rater=code_(p.rater),scores=p.scores||{};need_(Object.keys(scores).length===12&&Array.from({length:12},(_,i)=>String(i+1)).every(k=>Object.prototype.hasOwnProperty.call(scores,k)&&[0,1,2,3,null].includes(scores[k])),'Registra 12 puntuaciones 0–3 o null.');need_(!d.scores.some(r=>r.response_id===p.response_id&&r.rater===rater),'Este evaluador ya calificó la respuesta.');d.scores.push({id:id_(),response_id:p.response_id,rater,scores:JSON.stringify(scores),note:String(p.note||'').slice(0,4000),created_at:now_()});return {ok:true};}
 if(action==='release'){need_(!frozen_(d),'La intervención está congelada.');need_(CATALOG[p.instrument]&&String(p.evidence||'').trim().length>=20,'Registra instrumento y evidencia verificable de validación.');d.releases[p.instrument]={instrument:p.instrument,version:CATALOG[p.instrument].version,status:'validated',evidence:p.evidence,created_at:now_()};return record_(d,'release',p.instrument,'','',{evidence:p.evidence});}
 if(action==='freeze'){const cohort=code_(p.cohort),m=p.metadata||{};need_(['protocol','balanced_forms','contents','sessions','minutes_per_session','ethics_reference','vp1_decision','vp2_decision','retention_until'].every(k=>String(m[k]||'').trim()),'Completa todos los datos del protocolo.');need_(Object.keys(CATALOG).every(k=>d.releases[k]?.status==='validated'),'Valida los seis instrumentos.');need_(!d.cohorts.some(x=>x.id===cohort),'Cohorte ya congelada.');d.cohorts.push({id:cohort,phase:'intervention',manifest:JSON.stringify(manifest_(d)),metadata:JSON.stringify(m),created_at:now_()});return {ok:true};}
 if(action==='erase'){const subject=code_(p.subject);need_(p.confirm==='ELIMINAR '+subject&&person_(d,subject).withdrawn,'Registra el retiro y confirma ELIMINAR seguido del código.');const records=new Set(d.records.filter(r=>r.subject===subject).map(r=>r.id)),attempts=new Set(d.attempts.filter(r=>r.participant_code===subject).map(r=>r.attempt_id));d.scores=d.scores.filter(r=>!records.has(r.response_id));d.reviews=d.reviews.filter(r=>!attempts.has(r.attempt_id));for(const name of ['records','assignments'])d[name]=d[name].filter(r=>r.subject!==subject);for(const name of ['missions','attempts','events','responses'])d[name]=d[name].filter(r=>r.participant_code!==subject);for(const name of ['people','accounts','states','profiles'])delete d[name][key_(subject)];for(const name of ['modules','sessions','drafts','tokens'])for(const k of Object.keys(d[name]))if([d[name][k].participant_code,d[name][k].subject,d[name][k].code].includes(subject))delete d[name][k];d.operations={};return {ok:true,notice:'Retirado de la base activa. Revisa copias anteriores y cachés según la política de conservación.'};}
 fail_('Operación de estudio no encontrada.',404);
}
function stats_(vals,max){const nums=vals.filter(v=>typeof v==='number').sort((a,b)=>a-b),n=nums.length,quant=q=>{const t=(n-1)*q,i=Math.floor(t);return nums[i]+(nums[Math.min(i+1,n-1)]-nums[i])*(t-i);},r={n,missing:vals.filter(v=>v==null).length,not_applicable:vals.filter(v=>['N/A','N/O'].includes(v)).length,counts:{}};for(const v of vals)r.counts[String(v)]=(r.counts[String(v)]||0)+1;if(n)Object.assign(r,{mean:nums.reduce((a,b)=>a+b,0)/n,median:quant(.5),iqr:quant(.75)-quant(.25),favorable_pct:max===5?100*nums.filter(x=>x>=4).length/n:null});return r;}
function summary_(d){
 const out={content:{},prototype:{},pilot:{},applications:{},agreement:[]},latest={};for(const r of d.records)if(['content','prototype','pilot'].includes(r.kind))latest[[r.kind,r.instrument,r.version,r.subject,r.occasion].join('|')]=r;const groups={};for(const r of Object.values(latest)){const k=[r.kind,r.instrument,r.version,r.occasion].join('|');(groups[k]||(groups[k]=[])).push(JSON.parse(r.payload));}
 for(const [key,rows]of Object.entries(groups)){const [kind,iid,ver,occasion]=key.split('|'),target={},doc=CATALOG[iid];for(const item of kind==='content'?doc.validation_units:doc.items){if(kind==='content'){target[item.id]={};for(const attr of ['clarity','relevance','representativeness',...(item.equivalence?['equivalence']:[])]){const vals=rows.map(r=>r.ratings[item.id]?.[attr]),s=stats_(vals,5),nums=vals.filter(v=>typeof v==='number'),v=nums.length?nums.reduce((n,x)=>n+x-1,0)/(nums.length*4):null;target[item.id][attr]={...s,aiken_v:v,decision:v===null?'sin datos':v>=.8?'mantener':v>=.7?'revisar':'reformular'};}}else{const s=stats_(rows.map(r=>r.answers[item.id]),kind==='pilot'?2:5);if(kind==='prototype'&&s.n)Object.assign(s,{decision:s.mean<3||s.favorable_pct<60?'modificar':s.mean>=4&&s.favorable_pct>=80?'mantener':'revisar',review_disagreement:s.iqr>=2,review_panel:s.not_applicable/rows.length>=.3});if(kind==='pilot'&&s.n)s.observed_achievement_pct=s.mean/2*100;target[item.id]=s;}}out[kind][[iid,ver,occasion].join('/')]=target;}
 for(const r of d.records.filter(r=>r.kind==='application'))out.applications[r.id]={instrument:r.instrument,subject:r.subject,occasion:r.occasion,form:JSON.parse(r.payload).form,raters:[]};const groupsR={};for(const r of d.scores){const s=JSON.parse(r.scores),vals=Object.values(s),dims={};for(let i=0;i<4;i++){const v=[1,2,3].map(j=>s[String(i*3+j)]);dims[String(i+1)]=v.every(x=>x!==null)?v.reduce((a,b)=>a+b,0):null;}out.applications[r.response_id]?.raters.push({rater:r.rater,total:vals.every(v=>v!==null)?vals.reduce((a,b)=>a+b,0):null,dimensions:dims});(groupsR[r.response_id]||(groupsR[r.response_id]=[])).push({rater:r.rater,s});}for(const [rid,rs]of Object.entries(groupsR))for(let i=0;i<rs.length;i++)for(let j=i+1;j<rs.length;j++){const a=rs[i],b=rs[j],keys=Object.keys(a.s).filter(k=>a.s[k]!==null&&b.s[k]!==null);out.agreement.push({response_id:rid,raters:[a.rater,b.rater],paired_items:keys.length,exact_agreement:keys.length?keys.filter(k=>a.s[k]===b.s[k]).length/keys.length:null,discrepant_items:keys.filter(k=>a.s[k]!==b.s[k])});}return out;
}
