function dashboard_(d){
 const accounts=Object.values(d.accounts),today=now_().slice(0,10),sessions=Object.values(d.sessions),todayS=sessions.filter(s=>s.started_at.startsWith(today));
 const parts=accounts.map(a=>{const state=d.states[key_(a.participant_code)]||{},comp=competence_(state),valid=DIMS.filter(k=>comp[k].tasks),weak=valid.length?valid.reduce((a,b)=>comp[a].level<comp[b].level?a:b):'problem',missions=d.missions.filter(m=>m.participant_code===a.participant_code);return {participant_code:a.participant_code,grade:a.grade,competence:comp,mastery:Object.fromEntries(DIMS.map(k=>[k,comp[k].level===null?0:(comp[k].level-1)*100/3])),weakest:weak,weakest_label:PLANS[weak].label,weakest_score:comp[weak].level===null?0:(comp[weak].level-1)*100/3,mission_count:missions.length,adaptive_passed:Object.values(state.taskEvidence||{}).filter(e=>!e.provisional&&DIMS.every(k=>e.rubric[k]>=3)).length,effective_minutes:Math.round(sessions.filter(s=>s.participant_code===a.participant_code).reduce((n,s)=>n+s.effective_ms,0)/6000)/10,status:valid.length?'Evidencia en desarrollo':'Pendiente de evidencia docente',suggested_modules:['Resolver retos cotidianos']};});
 const attempts=d.attempts.slice(-50).reverse().map(a=>({...a,teacher_review:d.reviews.filter(r=>r.attempt_id===a.attempt_id).slice(-1)[0]||null})),pending=d.attempts.filter(a=>!d.reviews.some(r=>r.attempt_id===a.attempt_id)).length,avg={},n={};for(const k of DIMS){const rows=parts.filter(p=>p.competence[k].tasks);n[k]=rows.length;avg[k]=rows.length?rows.reduce((s,p)=>s+p.mastery[k],0)/rows.length:0;}
 return {summary:{registered_students:accounts.length,participants:parts.length,missions_generated:d.missions.length,app_version:APP_VERSION,access_mode:'online',storage:'Google Sheets',db_size_mb:Math.round(JSON.stringify(d).length/10485.76)/100,document_index:'BM25',documents_loaded:d.documents.length,document_chunks:d.documents.reduce((n,x)=>n+x.chunks.length,0),model_available:false,mastery_avg:avg,mastery_n:n,research:{today_participants:new Set(todayS.map(s=>s.participant_code)).size,today_sessions:todayS.length,today_minutes:Math.round(todayS.reduce((n,s)=>n+s.effective_ms,0)/6000)/10}},participants:parts,student_accounts:accounts.map(a=>({participant_code:a.participant_code,grade:a.grade,has_progress:d.missions.some(m=>m.participant_code===a.participant_code)||Object.values(d.modules).some(m=>m.participant_code===a.participant_code),last_seen:sessions.filter(s=>s.participant_code===a.participant_code).map(s=>s.last_seen).sort().slice(-1)[0]||''})),teacher_insights:{participants:parts,pending_review_count:pending,needs_support:parts.filter(p=>p.weakest_score<67),recent_events:d.events.slice(-30).reverse()},recent_attempts:attempts,recent_missions:d.missions.slice(-40).reverse(),research_config:d.config,instruments:Object.values(d.instruments).map(i=>({...i,items:i.items.length,responses:d.responses.filter(r=>r.instrument_id===i.instrument_id).length})),technical:{platform:'Google Apps Script',storage:'Google Sheets',model_used:false,version:APP_VERSION}};
}
function banks_(d,path,p,params,get,teacher){
 if(path==='/api/teacher/question_banks')return {modules:Object.values(BANKS).filter(b=>b.moduleKey!=='forces').map(b=>({key:b.moduleKey,title:MODULES.find(m=>m.key===b.moduleKey)?.title||b.title||b.moduleKey,icon:MODULES.find(m=>m.key===b.moduleKey)?.icon||'',questions:b.units.reduce((n,u)=>n+u.questions.length,0)}))};
 const module=p.module||params.module;need_(Object.prototype.hasOwnProperty.call(BANKS,module),'Módulo no encontrado.',404);const current=d.banks[module]||BANKS[module],backups=d.backups[module]||[];
 if(get)return path.endsWith('/backups')?{backups:backups.map(x=>({name:x.name,created_at:x.at}))}:{bank:current,backups:backups.map(x=>({name:x.name,created_at:x.at})),issues:[]};
 need_(teacher,'Acceso docente requerido.',403);let bank=p.bank;if(path.endsWith('/restore')){const found=backups.find(x=>x.name===p.backup);need_(found,'Copia no encontrada.',404);bank=found.bank;}
 need_(bank&&bank.moduleKey===module&&Array.isArray(bank.units)&&bank.units.length>0&&JSON.stringify(bank).length<1000000,'Banco inválido.');const ids=new Set();for(const u of bank.units){need_(Array.isArray(u.questions)&&u.questions.length&&u.title,'Etapa incompleta.');for(const q of u.questions){need_(q.id&&!ids.has(q.id)&&String(q.prompt||'').trim(),'Pregunta incompleta o identificador repetido.');ids.add(q.id);if(q.type==='choice'){need_(Array.isArray(q.options)&&q.options.length>=2&&q.options.length<=8,'Opciones inválidas.');const norm=s=>String(s).trim().toLocaleLowerCase(),opts=q.options.map(norm);need_(opts.every(Boolean)&&new Set(opts).size===opts.length&&opts.filter(o=>o===norm(q.answer)).length===1,'Respuesta correcta u opciones inválidas.');}else if(q.type==='truefalse')need_(['Verdadero','Falso'].includes(q.answer),'Respuesta inválida.');else if(['short','hangman'].includes(q.type))need_(String(q.answer||'').trim(),'Falta respuesta.');else if(['memory','match'].includes(q.type))need_(Array.isArray(q.pairs)&&q.pairs.length>=2,'Faltan parejas.');else if(q.type==='order')need_(Array.isArray(q.items)&&q.items.length>=2,'Faltan pasos.');else fail_('Tipo de pregunta no reconocido.');}}
 const name=module+'-'+id_();backups.push({name,at:now_(),bank:clone_(current)});d.backups[module]=backups;d.banks[module]=clone_(bank);return {ok:true,backup:name};
}
function instruments_(d,path,p,c,get){
 if(path==='/api/instruments/active')return {instruments:Object.values(d.instruments).filter(i=>i.active&&i.audience==='student').map(i=>({...i,answered:d.responses.some(r=>r.instrument_id===i.instrument_id&&r.participant_code===c)}))};need_(!get,'Método inválido.');
 if(path.endsWith('/upload')){const i=p.definition;need_(i&&/^[A-Za-z0-9_-]{1,64}$/.test(i.instrument_id||'')&&i.title&&Array.isArray(i.items)&&i.items.length,'Definición inválida.');const ids=new Set();for(const q of i.items){need_(q.id&&!ids.has(q.id)&&q.prompt&&['likert5','single','text'].includes(q.type),'Ítem inválido o repetido.');if(q.type==='single')need_(Array.isArray(q.options)&&q.options.length>=2,'Faltan opciones.');ids.add(q.id);}d.instruments[i.instrument_id]={...i,active:!!p.active};return {ok:true,instrument:i};}
 const i=d.instruments[p.instrument_id];need_(i,'Instrumento no encontrado.',404);if(path.endsWith('/toggle')){i.active=!!p.active;return {ok:true};}
 need_(i.active&&i.audience==='student','Instrumento no disponible.');need_(!d.responses.some(r=>r.instrument_id===i.instrument_id&&r.participant_code===c),'Ya enviaste este instrumento.',409);const answers={};for(const q of i.items){let v=(p.answers||{})[q.id];if(q.type==='likert5'){v=Number(v);need_(Number.isInteger(v)&&v>=1&&v<=5,'Respuesta Likert inválida.');}else if(q.type==='single')need_(i.items.find(x=>x.id===q.id).options.includes(v),'Opción inválida.');else v=String(v||'').slice(0,1500);answers[q.id]=v;}d.responses.push({instrument_id:i.instrument_id,participant_code:c,answers,created_at:now_()});return {ok:true};
}
function words_(text){return String(text||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').match(/[a-z0-9]{3,}/g)||[];}
function documents_(d,path,p,get){
 if(path==='/api/upload_pdf'){
  need_(!get,'Método inválido.');const b64=String(p.data_base64||'');need_(b64.length<4000000,'En esta edición, usa PDF de hasta 3 MB.');const bytes=Utilities.base64Decode(b64);need_(bytes.length>5&&bytes.slice(0,5).map(b=>String.fromCharCode(b)).join('')==='%PDF-','El archivo no es PDF.');
  const name=String(p.filename||'documento.pdf').replace(/[^A-Za-z0-9._-]/g,'_').slice(0,120),start=Date.now();let converted;
  try{converted=Drive.Files.create({name:'PRISMA extracción temporal '+name,mimeType:'application/vnd.google-apps.document'},Utilities.newBlob(bytes,'application/pdf',name),{fields:'id'});const r=UrlFetchApp.fetch('https://www.googleapis.com/drive/v3/files/'+converted.id+'/export?mimeType=text%2Fplain',{headers:{Authorization:'Bearer '+ScriptApp.getOAuthToken()},muteHttpExceptions:true});need_(r.getResponseCode()===200,'No se pudo extraer el texto del PDF.');const text=r.getContentText();need_(text.trim().length>30,'El PDF no produjo texto legible.');const chunks=text.match(/[\s\S]{1,1100}/g)||[];const doc={filename:name,data_base64:b64,chunks,created_at:now_()};d.documents=d.documents.filter(x=>x.filename!==name);d.documents.push(doc);return {filename:name,chunks:chunks.length,index:'BM25',index_ms:Date.now()-start};}
  finally{if(converted)Drive.Files.update({trashed:true},converted.id);}
 }
 if(path==='/api/clear_docs'||path==='/api/clear_documents'){need_(!get,'Método inválido.');d.documents=[];return {ok:true};}
 const query=[...new Set(words_(p.query))],corpus=d.documents.flatMap(doc=>doc.chunks.map(text=>({filename:doc.filename,page:'texto extraído; paginación no conservada',text,terms:words_(text)}))),avg=corpus.length?corpus.reduce((n,c)=>n+c.terms.length,0)/corpus.length:1;
 const sources=corpus.map(c=>{let score=0;for(const t of query){const tf=c.terms.filter(w=>w===t).length,df=corpus.filter(x=>x.terms.includes(t)).length;score+=Math.log(1+(corpus.length-df+.5)/(df+.5))*tf*2.5/(tf+1.5*(.25+.75*c.terms.length/avg));}return {...c,score};}).filter(c=>c.score>0).sort((a,b)=>b.score-a.score).slice(0,Math.max(1,Math.min(6,Number(p.k)||4))).map(({terms,...c})=>c);
 return {answer:sources.length?'Lee estos fragmentos y relaciona un dato con tu pregunta. La selección es documental; no es una respuesta generada por IA.':'No encontré fragmentos pertinentes. Cambia las palabras de la consulta o pide al docente revisar la biblioteca.',sources,source:'biblioteca-bm25'};
}
function csv_(rows){const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];function cell(x){let t=typeof x==='object'?JSON.stringify(x):String(x??'');if(/^[=+@\-\t\r]/.test(t))t="'"+t;return '"'+t.replace(/"/g,'""')+'"';}return '\ufeff'+[keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n');}
function escape_(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function export_(d,path,kind){
 const tables={overview:dashboard_(d).participants,attempts:d.attempts,interactions:d.events,missions:d.missions,reviews:d.reviews,teacher_reviews:d.reviews,sessions:Object.values(d.sessions),research_sessions:Object.values(d.sessions),research_events:d.events,instrument_responses:d.responses,expert_validations:d.events.filter(x=>x.event_type==='expert_validation'),...studyData_(d)};
 Object.assign(tables,{participants:dashboard_(d).participants,master:d.attempts.map(a=>({...a,profile:d.profiles[key_(a.participant_code)]||{},study:person_(d,a.participant_code)})),events:d.events,modules:Object.values(d.modules),experts:d.events.filter(e=>e.event_type==='expert_validation'),instruments:d.responses,benchmarks:d.benchmarks||[]});
 const report='<!doctype html><html lang="es"><meta charset="utf-8"><title>Informe PRISMA</title><style>body{font:16px system-ui;margin:30px}table{border-collapse:collapse}td,th{padding:10px;border:1px solid #bbb}</style><h1>PRISMA · Informe docente</h1><p>'+escape_(now_())+' · '+escape_(APP_VERSION)+'</p><p>La orientación predeterminada no acredita dominio. Los niveles proceden de revisiones docentes.</p><table><tr><th>Código</th><th>Grado</th><th>Retos</th><th>Evidencia</th></tr>'+tables.overview.map(p=>'<tr><td>'+escape_(p.participant_code)+'</td><td>'+escape_(p.grade)+'</td><td>'+p.mission_count+'</td><td>'+escape_(JSON.stringify(p.competence))+'</td></tr>').join('')+'</table></html>';
 if(path.endsWith('report.html'))return {file:{mime:'text/html;charset=utf-8',text:report}};
 if(path.endsWith('export.csv')){need_(tables[kind],'Tipo de exportación no reconocido.');return {file:{mime:'text/csv;charset=utf-8',text:csv_(tables[kind])}};}
 const blobs=Object.entries(tables).map(([k,rows])=>Utilities.newBlob(csv_(rows),'text/csv',k+'.csv'));blobs.push(Utilities.newBlob(report,'text/html','INFORME_DOCENTE.html'));blobs.push(Utilities.newBlob(JSON.stringify({version:APP_VERSION,exported_at:now_(),...studyData_(d)},null,2),'application/json','estudio.json'));return {file:{mime:'application/zip',base64:Utilities.base64Encode(Utilities.zip(blobs,'PRISMA_DATOS.zip').getBytes())}};
}
function actualizarVistas(){
 const lock=LockService.getScriptLock();lock.waitLock(30000);try{const d=load_(),s=sheet_(),dash=dashboard_(d),tables={Estudiantes:dash.student_accounts,Retos_asignados:d.missions.map(m=>({codigo:m.participant_code,reto:m.mission_id,titulo:m.title,fecha:m.created_at})),Respuestas:d.attempts.map(a=>({codigo:a.participant_code,reto:a.mission_id,respuesta:a.answer,fecha:a.created_at})),Progreso:dash.participants.map(p=>({codigo:p.participant_code,competencia:p.competence})),Instrumentos:d.records.filter(r=>r.kind==='application'),Revisiones:d.reviews};for(const[name,rows]of Object.entries(tables)){const t=s.getSheetByName(name)||s.insertSheet(name),keys=rows.length?[...new Set(rows.flatMap(Object.keys))]:['Estado'];const values=[keys,...rows.map(r=>keys.map(k=>{const v=typeof r[k]==='object'?JSON.stringify(r[k]):String(r[k]??'');return "'"+v.slice(0,39000);} ))];t.clearContents();if(t.getMaxRows()<values.length)t.insertRowsAfter(t.getMaxRows(),values.length-t.getMaxRows());if(t.getMaxColumns()<keys.length)t.insertColumnsAfter(t.getMaxColumns(),keys.length-t.getMaxColumns());t.getRange(1,1,values.length,keys.length).setValues(values);t.setFrozenRows(1);}const estado=s.getSheetByName('Estado');if(estado)estado.getRange('A1:B2').setValues([['PRISMA Apps Script','Vistas de consulta'],['Actualización',now_()]]);return 'Vistas actualizadas. La copia integral está en las pestañas privadas _PRISMA_GAS.';}finally{lock.releaseLock();}
}
