// PRISMA: Tutor local y consultas a la biblioteca PDF indexada.
// PRISMA: Los comentarios documentan el flujo; no cambian datos, rutas API ni comportamiento.

(() => {
'use strict';
const SESSION_KEY='prismaHubSessionV1';
const $=id=>document.getElementById(id);
let session=null,health=null,toastTimer=null;
// PRISMA: Lee la sesion activa desde sessionStorage.
function readSession(){try{const s=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');return s?.code&&s?.grade&&s.verified===true?s:null}catch{return null}}
// PRISMA: Escapa texto antes de insertarlo en HTML para evitar que contenido externo se interprete como codigo.
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
// PRISMA: Muestra mensajes breves en los modulos.
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2300)}
// PRISMA: Limpia marcas de formato no deseadas antes de mostrar texto generado.
function cleanDisplay(text){let t=String(text||'').replace(/\r/g,'');t=t.replace(/```(?:json|markdown|text)?/gi,'').replace(/```/g,'').replace(/\*\*/g,'').replace(/__/g,'').replace(/`/g,'');t=t.replace(/^\s*#{1,6}\s*/gm,'').replace(/^\s*[-*+]\s+/gm,'• ').replace(/\n{3,}/g,'\n\n');return t.trimStart()}
// PRISMA: Lee el streaming NDJSON de Gemma y separa tokens, resultado final y errores.
async function streamNdjson(path,payload,onText){try{const body={...payload,participant_code:session?.code||payload.participant_code,grade:session?.grade||payload.grade,session_id:window.PRISMA_RESEARCH?.sessionId?.()||''};const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json',...(session?.studentToken?{'X-PRISMA-Student-Token':session.studentToken}:{})},body:JSON.stringify(body)});if(!r.ok)return null;const reader=r.body.getReader(),decoder=new TextDecoder();let pending='',raw='',finalData=null;for(;;){const {value,done}=await reader.read();pending+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=pending.split('\n');pending=lines.pop()||'';for(const line of lines){if(!line.trim())continue;let evt=null;try{evt=JSON.parse(line)}catch{continue}if(evt.type==='token'){raw+=evt.text||'';onText?.(cleanDisplay(raw))}else if(evt.type==='result')finalData=evt.data||null}if(done)break}return finalData}catch{return null}}
// PRISMA: Comprueba si Gemma y la biblioteca local estan disponibles.
async function getHealth(){if(location.protocol==='file:')return null;try{const r=await fetch('/api/health');return r.ok?await r.json():null}catch{return null}}
// PRISMA: Envia solicitudes JSON sencillas desde el asistente.
async function postJson(path,payload){if(location.protocol==='file:')return null;try{const body={...payload,participant_code:session?.code||payload.participant_code,grade:session?.grade||payload.grade,session_id:window.PRISMA_RESEARCH?.sessionId?.()||''};const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json',...(session?.studentToken?{'X-PRISMA-Student-Token':session.studentToken}:{})},body:JSON.stringify(body)});if(!r.ok)return null;return await r.json()}catch{return null}}
// PRISMA: Activa o desactiva el tutor segun el estado del motor local.
function setTutorEnabled(enabled){$('sendBtn').disabled=!enabled;$('chatInput').disabled=!enabled;$('tutorBadge').textContent=enabled?'Orientación predeterminada':'Sin conexión';$('tutorBadge').classList.toggle('disabled-note',!enabled)}
// PRISMA: Pregunta a la biblioteca PDF usando recuperacion local y Gemma.
async function askDocument(){const q=$('docQuestion').value.trim();if(!q){toast('Escribe una pregunta.');return}$('askDocBtn').disabled=true;$('docAnswer').textContent='';$('docAnswer').classList.remove('hidden');$('docAnswer').classList.add('streaming');let out=await streamNdjson('/api/ask_document_stream',{query:q,k:4},text=>{$('docAnswer').textContent=text});if(!out)out=await postJson('/api/ask_document',{query:q,k:4});$('docAnswer').classList.remove('streaming');$('askDocBtn').disabled=false;if(!out){toast('No pude consultar la biblioteca local.');return}$('docAnswer').textContent=cleanDisplay(out.answer||$('docAnswer').textContent);$('docSources').innerHTML=(out.sources||[]).map((s,i)=>`<div class="source-item"><strong>Fragmento ${i+1} · página ${s.page}</strong><small>${esc(s.text)}</small></div>`).join('')}
// PRISMA: Agrega un mensaje seguro al historial visual del chat.
function addMessage(role,text){const box=document.createElement('div');box.className=`chat-msg ${role}`;box.innerHTML=`<strong>${role==='user'?esc(session.code):'PRISMA'}</strong><p></p>`;box.querySelector('p').textContent=text;$('chatLog').appendChild(box);$('chatLog').scrollTop=$('chatLog').scrollHeight;return box.querySelector('p')}
// PRISMA: Procesa el texto escrito por el estudiante y solicita respuesta del tutor.
async function send(){const text=$('chatInput').value.trim();if(!text||health?.status!=='ok'||$('sendBtn').disabled)return;addMessage('user',text);$('chatInput').value='';const target=addMessage('assistant','');target.classList.add('streaming');$('sendBtn').disabled=true;let raw='';try{const r=await fetch('/api/generate_stream',{method:'POST',headers:{'Content-Type':'application/json',...(session?.studentToken?{'X-PRISMA-Student-Token':session.studentToken}:{})},body:JSON.stringify({prompt:text,participant_code:session.code,grade:session.grade,session_id:window.PRISMA_RESEARCH?.sessionId?.()||''})});if(!r.ok)throw new Error('Modelo no disponible');const reader=r.body.getReader(),decoder=new TextDecoder();for(;;){const {value,done}=await reader.read();if(done)break;raw+=decoder.decode(value,{stream:true});target.textContent=cleanDisplay(raw);$('chatLog').scrollTop=$('chatLog').scrollHeight}target.textContent=cleanDisplay(raw)}catch(e){target.textContent=`No pude generar la respuesta local: ${e.message||e}`}finally{target.classList.remove('streaming');$('sendBtn').disabled=false}}
// PRISMA: Inicializa la Ruta Adaptativa, comprueba sesion y carga la primera mision.
async function boot(){session=readSession();if(!session){location.replace('../../index.html');return}await window.PRISMA_RESEARCH?.start?.();session=window.PRISMA_RESEARCH?.readSession?.()||session;$('userCode').textContent=session.code;$('userGrade').textContent=`Grado ${session.grade}`;health=await getHealth();if(health?.status==='ok'){$('modelStatus').textContent=health.model_available?'Gemma 2 2B disponible':'Servidor PRISMA activo';const mode=health.access_mode==='lan'?'Acceso por red local del aula, sin depender de Internet.':'Guías predeterminadas y consulta de fragmentos de tus PDF; sin IA generativa.';$('modelDetail').textContent=mode;$('docStatus').textContent=health.documents_loaded?`Biblioteca persistente: ${health.documents_loaded} PDF · ${health.document_chunks} fragmentos ${health.document_index||'BM25'}.`:'La biblioteca todavía no tiene documentos indexados.';$('libraryCount').textContent=health.documents_loaded?`${health.documents_loaded} PDF curriculares disponibles`:'Biblioteca pendiente de preparación';setTutorEnabled(health.status==='ok')}else{$('modelStatus').textContent='Servidor PRISMA no iniciado';$('modelDetail').textContent='Abre PRISMA con uno de sus iniciadores.';setTutorEnabled(false)}}
$('askDocBtn').onclick=askDocument;$('sendBtn').onclick=send;$('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.ctrlKey)send()});boot();
})();
